// ═══════════════════════════════════════════════════════════════════════════════
// DIALOGHI DIVERTENTI - Storia completa con umorismo veneto
// Versione ESTESA con centinaia di personaggi fastidiosi
// ═══════════════════════════════════════════════════════════════════════════════

export const DIALOGS = {
  
  // ═══════════════════════════════════════════════════════════════════════════
  // INTRO - Casa a Canalborgo (con più persone fastidiose)
  // ═══════════════════════════════════════════════════════════════════════════
  intro: {
    start: [
      'Buongiorno, tesoro mio!',
      'Oggi è il giorno importante!',
      'Vai dal Professor Barcaro, ti aspetta!',
      'Stai attento e non litigare!',
      'Se perdi, vieni a casa che ti faccio il risotto!',
      '...Il risotto è finito, farò la polenta!',
      'E se anche la polenta è finita... faremo i bigoi!',
      'Ah, i bigoi! La vera comida veneta!',
      'E se i bigoi sono finiti... facciamo la pasta!',
      'E se la pasta è finita... facciamo il pane!',
      'E se il pane è finito... FACCIAMO LA SPESA!',
      'MA NON ORA! PRIMA IL PROFESSORE!',
      'E NON DIMENTICARE DI SALUTARE LA VICINA!',
      'Quella impicciona! Sa tutto di tutti!',
      'E anche del fornaio! E del barista!',
      'E DEL TIFO CALCISTICO!',
      'E delle partite! E delle fidanzate!',
      'E DELLE FIDANZATE DEGLI ALTRI!',
      'ODDIO QUANTA ROBA!',
      'MA NON TI PREOCCUPARE!',
      'IO TI VOGLIO BENE!',
      'E ANCHE TUO PADRE!',
      'QUALE PADRE?! NON HO CAPITO!',
      'TUTTO QUELLO CHE SO! È NEL DNA!',
    ],
    morning_routine: [
      'La colazione? Un spritz, ovviamente!',
      'Caffè e grappa, poi se magna!',
      'Pane e salame, e se magna!',
      'Un po\' di prosecco per iniziare la giornata!',
      'E poi un altro spritz. E un altro. E un altro.',
      'E poi il pranzo! Polenta e osei!',
      'E poi merenda! Un ciccheto!',
      'E poi aperitivo! Un spritzone!',
      'E poi cena! Risotto al nero!',
      'E poi dopocena! Un grappino!',
      'E poi notte! Con gli incubi della polenta!',
      'E POI SI RICOMINCIA!',
    ],
    neighbor_intro: [
      'EHI! VICINA IMPICCIONA ARRIVA!',
      'Buongiorno! Come stai?!',
      'Bene! E tu?!',
      'BENE! E I TUOI?!',
      'Chi?! I miei genitori?!',
      'SÌ! E I NONNI! E I ZII!',
      'E I COUSINS! E I GATTI!',
      'QUALI GATTI?!',
      'QUELLI DI TUA SORELLA!',
      'QUALE SORELLA?! NON HO SORELLE!',
      'ODDIO! E\' TERRIBILE!',
      'FAMMI CALMARE!',
      'OKAY! Ma poi mi racconti tutto!',
      'TUTTO! DAL PRINCIPIO!',
      'IL PRINCIPIO DI COSA?!',
      'DI TUTTO! È OVVIO!',
    ],
    professor: [
      'Ah, sei arrivato finalmente!',
      'Sono il Professor Barcaro!',
      'Studio i Besti da quando i canali erano più puliti!',
      'Ho 4 Besti leggendari per te!',
      'Sì, LEGGENDARI!',
      'Di solito sono troppo potenti per i principianti...',
      'Ma oggi ho fatto un\'eccezione!',
      'Perché TU hai qualcosa di speciale!',
      'Non so cosa, ma me lo sento!',
      'Ho avuto una visione... Tu salverai Venetia.',
      'Ma prima... scegli il tuo compagno!',
      'E prima ancora... la storia della mia famiglia!',
      'È lunga! Siediti!',
      'Mio nonno era un cuoco!',
      'Un cuoco bravissimo!',
      'Ma la polenta... la polenta era sempre bruciata!',
      'E allora ha pensato: e se catturo i Besti?!',
      'E così ha fatto! Ha catturato TUTTI!',
      'E ha fatto una polenta gigantona!',
      'Ma è bruciata ANCHE QUELLA!',
      'E poi è successa una cosa strana...',
      'Un Bestia enorme è apparso!',
      'Il DUX VENETIAE!',
      'E ha detto: SEI UN PAZZO!',
      'E mio nonno ha detto: LO SO!',
      'E il Dux ha detto: ALLORA SMETTI!',
      'E mio nonno ha detto: MAI!',
      'E il Dux ha detto: ALLORA MUORI!',
      'E mio nonno ha detto: NO GRAZIE!',
      'E il Dux ha detto: ALLORA VIVI PER SEMPRE!',
      'E mio nonno ha detto: MA CHE PALLE!',
      'Ecco! Questa è la storia!',
      '...Aspetta, mi sono perso!',
      'Ricominciamo!',
    ],
    professor_backstory: [
      'La mia famiglia ha una storia triste...',
      'Mio nonno... era il Dux Polenta.',
      'Ha fatto cose terribili, 50 anni fa.',
      'Ho dedicato la mia vita a rimediare.',
      'E tu... sei la mia speranza.',
      'Perdonami se non te l\'ho detto prima.',
      'Ma non è finita!',
      'Sai chi è tuo padre?!',
      'Non lo so! Non ho idea!',
      'È IL FRATELLO DEL DUx!',
      'QUALE FRATELLO?!',
      'QUELLO LÀ! Quello grasso!',
      'Mio padre è grasso?!',
      'NO! È TUO ZIO! O FRATELLO!',
      'È CONFUSO!',
      'LA VITA È CONFUSIONE!',
      'Ecco perché combatto!',
      'Per dare senso al caos!',
      'E alla polenta bruciata!',
      'CHE NON È MAI BRUCIATA!',
      'È SEMPRE CRUDA!',
      'QUESTO È IL PROBLEMA!',
    ],
    rival_appears: [
      'EHI! CI SONO ANCH\'IO!',
      'Sono MARCO, il tuo RIVALE!',
      'E voglio il Besti più forte!',
      'TU scegli per primo, io prendo quello che resta!',
      'Ahaha! Vedremo chi è più forte!',
      'E non pensare che sarò gentile!',
      'Il mio Besti sarà IL PIÙ FORTE!',
      'E PRIMA DI COMBATTERE!',
      'TI DICO LA MIA STORIA!',
      'No! NON VOGLIO!',
      'È lunga! Ma ti piacerà!',
      'MIO PADRE ERA UN CUOCO!',
      'Anche quello del Professor?!',
      'NO! IL TUO!',
      'QUALE?!',
      'QUELLO LÀ! Quello che faceva il risotto!',
      'Non so di chi parli!',
      'E IO NON LO SO! È CONFUSIONE!',
      'Ecco perché sono il rivale!',
      'PERCHÉ NESSUNO CAPISCE NIENTE!',
    ],
    rival_family: [
      'Sono il nipote del Professor Barcaro!',
      'E anche... il fratello del Dux Polenta.',
      'Sì, lo so. È una storia complicated.',
      'Ma combatto per redimere la mia famiglia.',
      'E tu mi aiuterai, che ti piaccia o no!',
      'E anche se non lo sai!',
      'E anche se non ti importa!',
      'E anche se sei stanco!',
      'E anche se devi studiare!',
      'E anche se devi lavorare!',
      'E anche se hai fame!',
      'E anche se hai sonno!',
      'E anche se piove!',
      'E anche se c\'è il sole!',
      'E anche se è lunedì!',
      'E anche se è domenica!',
      'E anche se è Natale!',
      'E anche se è Ferragosto!',
      'E anche se è il tuo compleanno!',
      'E anche se è il mio compleanno!',
      'E anche se è il compleanno del cane!',
      'QUALE CANE?!',
      'IL CANE DEL VICINO!',
      'QUELLO CON 3 ZAMPE!',
      'CHE NON ESISTE!',
      'ESISTE! L\'HO VISTO IO!',
      'QUANDO?!',
      'IERI! O L\'ALTRO IERI!',
      'O L\'ALTRO L\'ALTRO IERI!',
      'NON LO SO! È CONFUSO!',
    ],
    choosing: [
      'Hai scelto [BESTIA]!',
      'Ottima scelta! Questo Besti è...',
      '...il più forte di tutti! Ahaha!',
      'Marco: VA BENE! IO PRENDO OMBRASPRITZ!',
      'Il più forte, ovviamente!',
      'Prof. Barcaro: Ah, anche quello è forte!',
      'Marco: PRONTO PER COMBATTERE!',
      'Prof. Barcaro: Nella mia arena! Andiamo!',
      'E PRIMA! UN\'ALTRA STORIA!',
      'NOOOO!',
      'È BREVE! GIURO!',
      'Mio nonno aveva un cane...',
      'Il cane si chiamava... ehm...',
      'COME SI CHIAMAVA?!',
      'NON MI RICORDO! È STATO 50 ANNI FA!',
      'E IL CANE È MORTO!',
      'DA UN PEZZO!',
      'MA LO RICORDO BENE!',
      'AVEVA 4 ZAMPE!',
      'E 2 ORECCHIE!',
      'E 1 CODA!',
      'E 100 DENTI!',
      'FORSE 200!',
      'E UN OCCHIO SOLO!',
      'QUELLO ERA UN ALTRO CANE!',
      'E IL CANE NORMALE?!',
      'NON ESISTE IL CANE NORMALE!',
      'TUTTI I CANI SONO SPECIALI!',
      'COME I BESTI!',
      'E COME LA POLENTA!',
      'CHE È SEMPRE BRUCIATA!',
      'O CRUDA!',
      'O AMBRUCIACCHIATA!',
      'QUELLA È LA PEGGIORE!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRIMA BATTAGLIA - Contro Marco (con più caos)
  // ═══════════════════════════════════════════════════════════════════════════
  first_battle: {
    start: [
      'Marco: PREPARATI!',
      'Marco: Ti dimostrerò chi comanda qui!',
      'Marco: Seize the day! ...O qualcosa del genere!',
      'Marco: È ora di brillare!',
      'Marco: Non sarò gentile, frate!',
      'E PRIMA UN PO\' DI STORIA!',
      'NOOO!',
      'È BREVISSIMA!',
      'Una volta combattevo contro mio fratello...',
      'QUALE FRATELLO?!',
      'QUELLO LÀ!',
      'NON VEDO NESSUNO!',
      'È INVISIBILE!',
      'TUTTI I MIEI FRATELLI SONO INVISIBILI!',
      'PERCHÉ LI HO MANGIATI!',
      'COSA?!',
      'ÈRANO POLENTA!',
      'MANGIARE POLENTA, NON FRATELLI!',
      'ODDIO!',
      'PERDONAMI!',
      'NON È STATO ME!',
      'È STATO MIO NONNO!',
      'QUALE NONNO?!',
      'IL NONNO DELLA POLENTA!',
      'NON ESISTE UN NONNO DELLA POLENTA!',
      'ESISTE ORA! L\'HO APPENA INVENTATO!',
      'PERCHÉ?!',
      'PER STORIA! È PIÙ BELLO COSÌ!',
      'MA È CONFUSO!',
      'TUTTA LA VITA È CONFUSIONE!',
      'E ORA COMBATTIAMO!',
    ],
    mid_battle: [
      'Marco: Non male! Ma io sono più forte!',
      'Marco: OMBRASPRITZ! FAAAAACCIA!',
      'Marco: Ecco la potenza del leggendario!',
      'Marco: Arresiti! È inutile!',
      'E PRIMA! UNA MOSSA SPECIALE!',
      'QUAL È LA MOSSA SPECIALE?!',
      'LA MOSSA "NON CAPISCO NIENTE"!',
      'NON È UNA MOSSA!',
      'È UNA FILOSOFIA!',
      'E UN MODO DI VIVERE!',
      'E UN TIPO DI CIBO!',
      'QUALE CIBO È "NON CAPISCO NIENTE"?!',
      'LA POLENTA!',
      'PERCHÉ LA POLENTA È CONFUSA!',
      'COME ME!',
      'E COME TE!',
      'E COME TUTTI!',
      'E COME IL CANE!',
      'QUALE CANE?!',
      'IL CANE INVISIBILE!',
      'CHE NON ESISTE!',
      'ESISTE! È QUI!',
      'DOVE?!',
      'IN FRAME!',
      'QUALE FRAME?!',
      'IL FRAME DEL TEMPO!',
      'NON CAPISCO!',
      'NEMMENO IO!',
      'Ecco perché combatto!',
    ],
    victory: [
      'Marco: BEL COMBATTIMENTO!',
      'Marco: Sei... più forte di quello che pensavo!',
      'Marco: Ma non mollare! Ci rivedremo!',
      'Marco: Io intanto vado avanti!',
      'Marco: Arrivederci, frate! Ahaha!',
      'E LA STORIA NON È FINITA!',
      'QUAL È LA STORIA?!',
      'LA STORIA DELLA POLENTA!',
      'E DEL CANE!',
      'E DEI FRATELLI!',
      'E DEL NONNO!',
      'E DELLA NONNA!',
      'E DEL COUSIN!',
      'E DEL BESTIA!',
      'E DELLA STORIA!',
      'E DEL TEMPO!',
      'E DELLO SPAZIO!',
      'E DELLA POLENTA!',
      'ANCORA POLENTA?!',
      'SEMPRE POLENTA!',
      'È LA VITA!',
      'CHE È POLENTA!',
      'CHE È VITA!',
      'CHE È CONFUSIONE!',
      'CHE È BELLO!',
      'CHE È BRUTTO!',
      'CHE È TUTTO!',
      'E ORA VAI!',
      'E PRIMA SALUTA IL CANE!',
      'QUALE CANE?!',
      'TUTTI I CANI!',
      'ANCHE QUELLI INVISIBILI!',
      'ANCHE QUELLI MORTI!',
      'ANCHE QUELLI CHE NON ESISTONO!',
      'E ANCHE QUELLO VERO!',
      'QUAL È QUELLO VERO?!',
      'NON LO SO! È CONFUSIONE!',
      'Ecco perché combatto!',
      'Ecco perché vivo!',
      'Ecco perché la polenta è sempre bruciata!',
      'ODDIO! BASTA!',
      'VADO! SCAPPO!',
      'MA TORNERÒ!',
      'CON ALTRA STORIA!',
      'E ALTRA POLENTA!',
      'E ALTRO CANE!',
      'E ALTRA CONFUSIONE!',
      'CIAOOO!',
      '',
      'Prof. Barcaro: Finalmente è andato via!',
      'Prof. Barcaro: Era 3 ore che parlava!',
      'Prof. Barcaro: E non ha detto niente!',
      'Prof. Barcaro: Come sempre!',
      'Prof. Barcaro: Ora vai! Esplora CANALBORGO!',
      'Prof. Barcaro: E preparati!',
      'Prof. Barcaro: Perché TUTTI parlano!',
      'Prof. Barcaro: E NESSUNO ASCOLTA!',
      'Prof. Barcaro: È la vita!',
      'Prof. Barcaro: È Venetia!',
      'Prof. Barcaro: È LA POLENTA!',
    ],
    lose: [
      'Marco: AHA! VEDI?! IO SONO IL PIÙ FORTE!',
      'Marco: Ma non preoccuparti...',
      'Marco: La rivincita arriverà!',
      'Marco: Vai a curare i tuoi Besti!',
      'Marco: Ci rivedremo presto!',
      'E INTANTO...',
      'TI CONTO UNA STORIA!',
      'NOOO!',
      'È BREVISSIMA!',
      'C\'era una volta...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      '...e poi...',
      'FINE!',
      'ERANO 200 "E POI"!',
      'E LA STORIA?',
      'NON C\'ERA!',
      'È QUELLA LA STORIA!',
      'IL NIENTE!',
      'È BELLO IL NIENTE!',
      'COME LA POLENTA!',
      'QUELLA CHE NON C\'È!',
      'PERCHÉ È BRUCIATA!',
      'O CRUDA!',
      'O INVISIBILE!',
      'COME IL CANE!',
      'E I FRATELLI!',
      'E LA STORIA!',
      'CIAOOO!',
    ],
  },

  // CANALBORGO - NPC Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  canalborgo: {
    mom: [
      'Tesoro! Come è andata?',
      'Hai fatto il bravo dal Professor Barcaro?',
      'Quando torni, c\'è il risotto!',
      'E se non torni... beh, mangio io!',
      'I Besti sono tuoi amici, trattali bene!',
      'E non dimenticare: la mamma ti ama!',
    ],
    fisherman: [
      'Sto pescando da 30 anni!',
      'I pesci de canalboro xe i migliori!',
      'Una volta ho visto un Bestia grandissimo!',
      'Sembrava un serpente, ma coi tentacoli!',
      'L\'ho chiamà "Canalord", perché el regnava sul canal!',
      'Se lo vedi, dimme, che gò curiosità!',
    ],
    tourist: [
      'Venezia xe tanto bela!',
      'I canali i ga propio ragion!',
      'El vaporetto xe in ritardo. Sempre.',
      'Questo gelato? Buonissimo!',
      'Le maschere? Le compre a Murano!',
      'Il Carnevale xe il periodo migliore!',
    ],
    shop_owner: [
      'Benvenuto nel mio store!',
      'Gli affari van mal, ma se sopravive!',
      'Proa el mio spritz, xe el pì buono!',
      'Le capture balls? Le ga un sapor strano...',
      'Ma funzionano! Credimi!',
      'Compra! Compra! El tempo xe denaro!',
    ],
    old_man: [
      'Xe 80 anni che vivo qui!',
      'Una volta i canali i era più pulii...',
      'E i gondolieri i cantava mejo!',
      'I giovani d\'ogo i sa niente!',
      'Anca i Besti i era più forti!',
      '...O forse sono io che son diventà più veccio!',
    ],
    kid: [
      'Mamma! Mamma! Voglio un Bestia!',
      'Quello verde! No, quello blu!',
      'TUTTI! Voglio tutti i Bestia!',
      'Quando sarò grande, sarò come te!',
      'Sarò il più forte di tutti!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPRITZIA - La Città dell'Aperitivo
  // ═══════════════════════════════════════════════════════════════════════════
  spritzia: {
    bartender: [
      'Bevi uno spritz!',
      'El spritz xe la vita!',
      'Senza spritz, no se pol vivar!',
      'Un aperitivo al giorno toglie il medico di torno!',
      'El mejo spritz? Quello che offro io!',
      'Happy hour! Dalle 6 alle 7! Dalle 5 alle 6! Sempre!',
    ],
    gondolier: [
      'Vogar no xe easy!',
      'El Canal Grande xe lunghissimo!',
      'Una volta gò portao un Doge!',
      'E\'stato il Doge più belo che gò mai vogiù!',
      'Xe restà su la gondola per 3 ore!',
      '...Non el ricordo più. Ma surely xe stà belo!',
    ],
    gelataio: [
      'Gelato fresco!',
      'El gelato de Spritzia xe famoso!',
      'Semper in coda, ma ne capita!',
      'Gusto spritz? Xe el mio preferio!',
      'E\'nato dalla mia testa! Genialità pura!',
      'Chi ga mai pensà a gelato e spritz insieme?!',
    ],
    tourist_1: [
      'Che meraviglia!',
      'I gondolieri cantano così bene!',
      'E lo spritz? Decisamente troppo buono!',
      'Tornerò sicuramente!',
      'Ho già i biglietti per il ritorno... che spreco!',
    ],
    tourist_2: [
      'Scusa, dove xe el vaporetto?',
      'Ah, quello è un canale. Ops.',
      'Mia moglie ga ragione, so proprio un ciucco!',
      'Almeno el spritz el compensa!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPAGNIA DELLA POLENTA - I cattivi
  // ═══════════════════════════════════════════════════════════════════════════
  compagnia: {
    grunt_appears: [
      'ALTO LÀ, GIOVINOTTO!',
      'Sono un GRINT della COMPAGNIA DELLA POLENTA!',
      'Noi vogliono...',
      '...creare la POLENTA DEFINITIVA!',
      'E per farlo, ci servono TUTTI i Besti della regione!',
      'AHAHAHAHA!',
      'O forse... solo quelli forti!',
      'Quello che hai tu, per esempio, pare interessante!',
    ],
    grunt_fight: [
      'Prima le presentazioni!',
      'Ecco el mio bestio!',
      'El xe nato nel fango!',
      'Come la polenta! AHAHAHA!',
    ],
    grunt_escape: [
      'ARGHHH! SEI TROPPO FORTE!',
      'Ma non importa!',
      'LA COMPAGNIA È OVUNQUE!',
      'Presto controllaremos TUTTO!',
      'AHAHAHAHA!',
      'El Dux sarà fiero de ti... quando te gnarà in catene!',
    ],
    grunt_defeat: [
      'NOOO! Gò perso!',
      'Ma el Dux gavà rason...',
      'Sei più forte de quello che pensavo.',
      'Non importa. Noi semo tanti.',
      'E el Dux xe immortale!',
      'AHAHAHAHA!',
    ],
    dux_intro: [
      'BENE BENE BENE...',
      'Il giovane Allenatore è arrivato fin qui!',
      'Sono DUX POLENTA, il leader supremo!',
      'La COMPAGNIA DELLA POLENTA regnerà su Venetia!',
      'E TU non puoi fermarci!',
      'AHAHAHAHA!',
      'O forse... sì? Questo sara interesante.',
    ],
    dux_plan: [
      'Il nostro piano è semplice!',
      'USEREMO il potere dei Besti leggendari...',
      '...per cucinare la POLENTA DELLE POLENTE!',
      'Sì, la polenta più grande, più dorata, più SAPPOROSA!',
      'E quando sarà pronta...',
      '...DOMINEREMO IL MONDO!',
      'E tu sarai il mio ingredienti segreto...',
      'L\'energia vitale dei giovani.',
    ],
    dux_thoughts: [
      'Perché ti combato? Per necessità.',
      'La polenta xe la mia vita.',
      'E tu... sei solo un ostacolo.',
      'Ma ammetto... sei forte.',
      'Forse troppo forte.',
    ],
    dux_defeated: [
      'NOOOO!',
      'LA MIA POLENTA!',
      'È BRUCIATA!',
      'PERCHÉ È SEMPRE BRUCIATA?!',
      'GRINT: DUX! LA POLENTA È BRUCIATA!',
      'TUTTI I GRINT: LA POLENTA È BRUCIATA!',
      'Dux: NOOOO! PERCHÉ?!',
      '',
      'Hai salvato VENETIA dalla polenta!',
    ],
    dux_redemption: [
      'Aspetta...',
      'Forse... xe stà tutto sbaglià.',
      '50 anni a cercar la polenta perfetta...',
      'E non ho mai considerà...',
      '...che forse la polenta perfetta...',
      '...xe quella che se fa co\' l\'amore.',
      'Grazie, giovane.',
      'Per avermi fermà.',
      'E forse... salvà.',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GYM LEADER - Dialoghi dettagliati
  // ═══════════════════════════════════════════════════════════════════════════
  gym_leaders: {
    bepi_spritzaro: {
      intro: [
        'CHEEE... BEVEMO OGGI?!',
        'Sono BEPI LO SPRITZIARO!',
        'Il re dell\'Happy Hour!',
        'Ho 47 spritz in corpo! *ride*',
        'Se vuoi il mio BADGE APERITIVO...',
        '...devi battermi PRIMA di un aperitivo!',
        'PERCHÉ DOPO NON RIESCO A COMBATTERE!',
        'Prima, però... un brindisi?',
      ],
      pre_battle: [
        'Hai rifiutato lo spritz?!',
        'Allora COMBATTIAMO!',
        'Spritzino! È ora de far festa!',
      ],
      during_battle: [
        'FAI PRESSIONE!',
        'Un altro spritz? NO, UN\'ALTRA MOSSA!',
        'Come el fuoco! Così se fa!',
        'Ecco la forza del alcohol!',
        '*ride* Questa xe bona!',
      ],
      defeat: [
        'Bel combattimento!',
        'Mi hai... *hic*... sconfitto!',
        'Ecco a te il BADGE APERITIVO!',
        'Ora vado a farmi un spritz!',
        'TU COMBATTIMENTO! *barcolla*',
      ],
      victory: [
        'VAI! VAI! VAI!',
        'PRONTO! UN\'ALTRO!',
        'AHAAH! BEL COMBATTIMENTO!',
        '*ride* Te se forte, giovane!',
        'Ma io son più forte! AHAHAH!',
      ],
    },

    giuliano_arena: {
      intro: [
        'BENVENUTO NELL\'ARENA!',
        'Sono Giuliano Arena, il leader!',
        'Come a Verona, dove gli innamorati giurano!',
        'Combattiamo con ONORE!',
        'Questa battaglia... è per lei.',
      ],
      pre_battle: [
        'Lei è ancora là fuori...',
        'La Compagnia l\'ha presa.',
        'Ma io non mi arrendo!',
        'Combatterò finché non la ritroverò!',
      ],
      during_battle: [
        'Non mollare!',
        'L\'amore ti dà forza!',
        'Ecco la potenza del cuore!',
        'Lei ti guarda! Dai il meglio!',
        'QUESTA È PER TE, AMORE MIO!',
      ],
      defeat: [
        'Bel combattimento, giovane!',
        'Hai vinto... ma la guerra continua.',
        'Ecco a te il BADGE ARENA!',
        'Prendi questa MT: VOLATA!',
        'Ti servirà per volare dai Besti.',
        'E... grazie per aver combattuto.',
      ],
      victory: [
        'NO! Ho perso!',
        'Lei... lei sarebbe delusa...',
        'Ma non mi arrendo!',
        'Riproverò! Per lei!',
        'Vai, giovane. Tu puoi salvarla.',
      ],
    },

    prof_sansovino: {
      intro: [
        'Benvenuto all\'Università!',
        'Sono il Professor Sansovino.',
        'Qui si studia... e si COMBATTE!',
        'La conoscenza è potere!',
        'Ma anche i Besti lo sono!',
      ],
      pre_battle: [
        'Ti racconterò una storia...',
        'Dopo averti SCONFITTO!',
        'La storia vera di Venetia!',
        'Quella che i libri non dicono!',
      ],
      during_battle: [
        'L\'esperienza è la migliore maestra!',
        'Studia bene le mie mosse!',
        'Questa è psicologia applicata!',
        'Non sottovalutare la teoria!',
        'La pratica senza teoria xe acqua!',
      ],
      defeat: [
        'Impressionante!',
        'Hai dimostrato la tua conoscenza!',
        'Ecco il BADGE STUDIO!',
        'Prendi anche la CARTA STUDENTE.',
        'Ti darà accesso a informazioni segrete.',
        'Ora vai. Il Dux ti aspetta.',
      ],
      victory: [
        'Hai vinto... ma non importa!',
        'La vera conoscenza non si misura in battaglia!',
        'Va\' via! Non ho tempo per i perdenti!',
        '*ride* Scherzo! Sei forte!',
      ],
    },

    nonna_gina: {
      intro: [
        'Benvenuta, giovane!',
        'Sono Nonna Gina!',
        'La natura xe la mia amica!',
        'E i Besti... i xe i me\' fradei!',
        'Combatteremo per la terra!',
      ],
      pre_battle: [
        'Le piante ti proteggeranno!',
        'Perché la natura xe sempre più forte!',
        'Del male non ne vogliamo far...',
        '...ma defenderci se pol!',
      ],
      during_battle: [
        'Cresci, mia pianta!',
        'Le radici ti trattengano!',
        'El sole ti dà forza!',
        'La natura non si arrende!',
        'Ecco l\'energia del verde!',
      ],
      defeat: [
        'Oh, bel combattimento!',
        'Hai un cuore verde!',
        'Ecco il BADGE RADICCIO!',
        'E anche un seme speciale...',
        'Il RADICCIO DORATO!',
        'Piantalo con amore!',
      ],
      victory: [
        'Hai vinto, ma la natura perdona!',
        'Non importa chi vince o perde...',
        'Conta l\'amore che ci metti!',
        'Va\' via, giovane. Sei benvenuto!',
      ],
    },

    regina_ghiacci: {
      intro: [
        'IL FREDDO È MIO ALLEATO!',
        'Sono la Regina dei Ghiacci!',
        'Regina di Dolomax, terra di neve!',
        'Solo i più forti possono passare!',
        'E tu... sei abbastanza forte?',
      ],
      pre_battle: [
        'Dolomitor dorme qui sotto...',
        'Lo spirito delle montagne.',
        'Se lo risvegli... potrebbe aiutarti.',
        'Ma prima, dimostra la tua forza!',
      ],
      during_battle: [
        'Il ghiaccio non perdona!',
        'Gela! Congela! DISTRUGGI!',
        'Il freddo xe eterno!',
        'Come la mia rabbia!',
        'NON TEMERE IL FREDDO!',
      ],
      defeat: [
        'Sei... forte...',
        'Forse troppo forte.',
        'Ecco il BADGE GHIACCIO!',
        'E anche... un segreto.',
        'Nella caverna c\'è Dolomitor.',
        'Svegliarlo sarà la tua scelta.',
      ],
      victory: [
        'IL FREDDO NON BASTA?!',
        'Impossibile!',
        '...Forse lo sottovalutavo.',
        'Va\' via. Hai vinto.',
      ],
    },

    maestro_marco: {
      intro: [
        'AH! Il giovane che ho sfidato ieri!',
        'Sei arrivato fin qui...',
        'Sono il MAESTRO MARCO!',
        'Il CAMPIONE di Venetia!',
        'Per battermi, devi passare la LEGA!',
      ],
      pre_battle: [
        'Frate... devo dirti qualcosa.',
        'Sono il fratello del Dux Polenta.',
        'Ho passato la vita a cercare di batterlo.',
        'Ma tu... tu puoi farlo.',
        'Combattiamo, frate. Dai il meglio!',
      ],
      during_battle: [
        'Non mollare!',
        'Questa è per la nostra famiglia!',
        'Combatti con tutto il cuore!',
        'Il sangue dei Barcaro xe forte!',
        'Ecco la forza del legame!',
      ],
      defeat: [
        'Bel combattimento, frate!',
        'Sei pronto per il Dux.',
        'Ecco il BADGE LAGO!',
        'Ora vai. Il tuo destino ti aspetta.',
        'E... grazie. Per tutto.',
      ],
      victory: [
        'Gò perso...',
        'Ma son fiero de ti, frate.',
        'Vai! Salva Venetia!',
        'Io crederò in te!',
      ],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ELITE FOUR - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  elite_four: {
    elite_1: {
      intro: [
        'Sono il PRIMO della Elite!',
        'Il FUOCO è la mia passione!',
        'Brucia tutto! Non fermarti mai!',
      ],
      battle: [
        'FAI CALDO! MOOOLTO CALDO!',
        'Il fuoco non si spegne!',
        'Ecco la fiamma!',
        'Brucia come me!',
      ],
      defeat: [
        'Il fuoco... si spegne...',
        'Ma un altro fuoco si accenderà...',
        'Bravo, giovane. Vai avanti.',
      ],
    },
    elite_2: {
      intro: [
        'L\'ACQUA è infinita!',
        'Come la mia forza!',
        'Ti sommergerò!',
      ],
      battle: [
        'INONDA!',
        'L\'acqua trova sempre una via!',
        'Ecco la marea!',
        'Nuota o affoga!',
      ],
      defeat: [
        'L\'acqua... rifluisce...',
        'Ma il mare non finisce mai.',
        'Continua, giovane.',
      ],
    },
    elite_3: {
      intro: [
        'La TERRA nutre tutti.',
        'Anche te.',
        'Ma prima... combatto!',
      ],
      battle: [
        'CRESCI!',
        'Le radici ti trattengano!',
        'Ecco la forza della terra!',
        'La natura è eterna!',
      ],
      defeat: [
        'La terra... trema...',
        'Ma tornerà a riposare.',
        'Sei sulla buona strada.',
      ],
    },
    elite_4: {
      intro: [
        'La MAGIA è ovunque.',
        'E io la controllo.',
        'Preparati a essere... confuso.',
      ],
      battle: [
        'INCANTA!',
        'Confondi! Illudi! TRIPLICA!',
        'La magia non ha limiti!',
        'Ecco l\'illusione!',
      ],
      defeat: [
        'La magia... svanisce...',
        'Ma le illusioni restano.',
        'Sei pronto per Marco.',
      ],
    },
    champion: {
      intro: [
        'IMPRESSIONANTE!',
        'Sei arrivato fin qui.',
        'Ora affronta il CAMPIONE!',
        'Sono il MAESTRO MARCO!',
      ],
      pre_battle: [
        'Frate... è ora.',
        'Combattiamo come veri fratelli.',
        'Dai il meglio di te!',
        'E io darò il meglio di me!',
      ],
      battle: [
        'Non mollare!',
        'Il nostro sangue è forte!',
        'Ecco la potenza dei Barcaro!',
        'Combatti, frate!',
      ],
      defeat: [
        'Bel combattimento... frate...',
        'Hai vinto...',
        'Sei il nuovo CAMPIONE!',
        'Ora vai. Il Dux ti aspetta.',
        'In bocca al lupo.',
      ],
      victory: [
        'NO! Ho perso!',
        'Ma... sono fiero de ti.',
        'Vai, frate. Salva la nostra famiglia.',
      ],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // VERONARA - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  veronara: {
    opera_singer: [
      'LA VITA E\' UN OPERA!',
      'Vieni a sentir el mio concerto!',
      'Romeo e Giulietta? Quela xe de Verona!',
      'E\'stato qui che i se son innamorai!',
      'L\'amore xe eterno, come la musica!',
    ],
    pizza_maker: [
      'La pizza xe napoletana, ma la faccio alla veneta!',
      'Poca mozzarella, tanto osel!',
      'Un trancio? Xe sempre mejo!',
      'La pizza più bela? Quela de piazza!',
      'Ma gò i miei clienti, e i xe contenti!',
    ],
    totti_tifoso: [
      'FORZA VENEZIA! ...Scusa, ROMA!',
      'Hai visto la partita ieri? No? Peccato!',
      'El calcio xe la mia vita!',
      'E i Besti... i gioca anca a calze!',
      'Una volta gò visto un bestio tirarghe una penale...',
    ],
    don_bepi: [
      'Dio ti benedica, figliolo!',
      'I Besti? Li ha creati Lui pure!',
      'Vieni a messa la domenica!',
      'El prete ga sempre rason!',
      'E la polenta xe benedetta anca lei!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PADOANA - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  padoana: {
    student_1: [
      'Studio a Padoana!',
      'La Università xe la pì bella!',
      'Gò da dar 5 esami!',
      'E\'stà l\'esame de oggi? Me son scordà!',
      'Ma无所谓! C\'è sempre domani!',
    ],
    student_2: [
      'Gò 20 anni e gò 40 esami indietro!',
      'La laurea? La vedo lontana!',
      'Ma almeno i spritz costano poco!',
      'E\'sta\' notte gò studià... sì, tanto!',
      '...Ok, no. Ma gò bevuto tanto!',
    ],
    cameriera: [
      'Cosa desidera, caro?',
      'El caffè? Corretto o normale?',
      '...CORRETTO!',
      'Un trancio de pizza? Xe freschissimo!',
      'O un risotto? El xe de oggi!',
    ],
    painter: [
      'Pingo come Tiziano!',
      'I colori i xe tuti nel mio studio!',
      'La mia Gioconda xe pì bella!',
      'E\'manca solo el sorriso! ...E la faccia!',
      'Ma la tecnica xe lì!',
    ],
    professor: [
      'L\'università xe el futuro!',
      'E i Besti? I xe el presente!',
      'Combina i du e ottieni el megio!',
      'Studia! Impara! DIVENTA FORTE!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TREVISELLA - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  trevisella: {
    farmer: [
      'La campagna xe bona!',
      'El radicchio xe el mio!',
      'La polenta xe sempre pronta!',
      'Questa terra la gavevo mia nona!',
      'E la gavevo gò anca mi!',
    ],
    nonno_piero: [
      'Xe 90 anni che vivo qui!',
      'E ancora non capisso perché piove!',
      'El radicchio? Quelo vero xe solo mio!',
      'I altri i ga el radicchio... el mio xe speciale!',
      'Perché el xe stà benedetto dal prete!',
    ],
    winemaker: [
      'El vin xe bonissimo!',
      'Proa el mio prosecco!',
      'Un gotto e se parla!',
      'Questo prosecco? L\'ho fatto io!',
      'E\'nato dalle mie uve!',
      'E dalle mie lacrime! ...No, scherzo!',
    ],
    sior_tonic: [
      'El pesce xe finio!',
      'Una volta i pesci i xeata infiniti!',
      'Ora bisogna aspettare che i torni.',
      'O pescare da un\'altra parte!',
      'O comprarli dal mercato!',
    ],
    cugino_max: [
      'EHI COUSIN!',
      'Tieni questa BICI!',
      'L\'ho rubata a mio cugino!',
      'Non dire niente a nessuno!',
      'E PS: son io tuo cugino. Infatti.',
      'Ecco perché la gavevo! AHAHAH!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOLOMAX - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  dolomax: {
    climber: [
      'Le Dolomiti xe le pì belle!',
      'El sole el pol far mal!',
      'Gò conquistao 50 cime!',
      'E altre 50 le gò solo guardae!',
      'Ma le xe belle lo stesso!',
    ],
    shepherd: [
      'Le mie pecore xe content!',
      'El formaggio xe stagionao!',
      'La montagna xe casa mia!',
      'E le pecore? Le xe la mia famiglia!',
      'Ogni sera le me contà le stelle!',
      '...Ok, no. Ma le prova!',
    ],
    bepi_yeti: [
      'L\'ho visto! Il Yeti!',
      '...Era un Bestia Nevelet!',
      'Ma l\'ho visto lo stesso!',
      'E\'stava là, in fondo al bosco!',
      'E\'bel che el se veda!',
      'Cosi gò qualcosa da contà!',
    ],
    bepi_monte: [
      'Benvenuto in altura!',
      'Qui l\'aria xe fina!',
      'E i Besti i cognosse el fatto loro!',
      'El Dolomitor? El dorme soto!',
      'E quando el se sveglia... beh, speremo no!',
    ],
    mountain_guide: [
      'Sei qui per la montagna?',
      'Le cime le chiama!',
      'Ma stà attento! I pericoli i xe tanti!',
      'E el freddo... el xe spietà!',
      'Torna vivo, eh!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GARDALAGO - Dialoghi
  // ═══════════════════════════════════════════════════════════════════════════
  gardalago: {
    swimmer: [
      'El lago xe fredo!',
      'Una nuotada e son vivo!',
      'L\'acqua xe pì buona de la mare!',
      'E i pesci? I xe pì buoni!',
      'E i Besti? I xe pì forti!',
    ],
    fisherman_lake: [
      'Qua i pesi i xe pì boni!',
      'El luccio xe grandissimo!',
      'El lago el ga i suoi secreti!',
      'Una volta gò tirà su un bestio!',
      'El gavà 3 metri! ...O forse 2!',
      '...O forse 1! Ma el gavà fame!',
    ],
    gondoliere_eco: [
      'La Gondola d\'Oro? Prendila!',
      'Xe un regalo del Doge!',
      'O meglio... la gò trovà in canal!',
      'Ma el Doge el gaveva 10 de ste barche!',
      'Una in pì o in manco... chi se ne impota!',
    ],
    tourist_lake: [
      'Che bel lago!',
      'Le montagne reflection!',
      'Sembra una cartolina!',
      'E anca el spritz reflection!',
      'Quelo xe anca pì bel!',
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ESPRESSIONI E FRASI VENETE DIVERTENTI
  // ═══════════════════════════════════════════════════════════════════════════
  venetian_expressions: {
    greetings: [
      'Ciao, xe!',
      'Oi, come va?',
      'Bongioro! ...No, xeadsera!',
      'Ciaoo!',
      'Come stai, belòto?',
      'E\' bon? ...Nù, xeario?',
    ],
    reactions: [
      'Ma va là!',
      'Xe impossibile!',
      'Oddio!',
      'Nooo!',
      'EHHHH!',
      'Ma xeeeto?!',
      'Povero mi!',
      'Cossa?!',
      'Mamma mia!',
      'Santa Madonna!',
      'Gesù Cristo!',
    ],
    approvals: [
      'Belissimo!',
      'Bravo!',
      'Ottimo!',
      'Figo!',
      'Stupendo!',
      'Così se fa!',
      'Sei un mito!',
      'Te se fortissimo!',
    ],
    insults: [
      'Stupido!',
      'Maleducato!',
      'Bastardo!',
      'Povero scemo!',
      'Vai a casa!',
      'No te vergogni?!',
      'Cioco!',
      'Bofo!',
    ],
    food: [
      'Ho fame!',
      'Xe l\'ora de magnar!',
      'El risotto xe pronto!',
      'Polenta e osei!',
      'Un spritz e semo pari!',
      'El cibo xe la vita!',
    ],
    weather: [
      'Xe un tempo de merda!',
      'Piove! Sempre!',
      'El sol no se vede mai!',
      'Che freddo! Me gò i giacomi!',
      'Caldo! Semore!',
      'El tempo xe sempre cativo!',
    ],
    love: [
      'Te vojo ben!',
      'Sei el me\' amor!',
      'Ti xe tutto per mi!',
      'Un bacio!',
      'El cuore me scalda!',
    ],
    defeat: [
      'Gò perso!',
      'Bel combattimento!',
      'Sei più forte!',
      'La prossima volta!',
      'Niente da far!',
      'Altro che polenta!',
    ],
    victory: [
      'HO VINTO!',
      'XEAHHH!',
      'SONO IL PIÙ FORTE!',
      'Te gò batùo!',
      'Belissimo!',
      'AHAHAHAHA!',
    ],
    confusion: [
      'Cossa?',
      'No capisso!',
      'Ma come?',
      'Eh?',
      'Cosa?!',
      'Xe pazzesco!',
    ],
  },
}

// Get random venetian expression
// ═══════════════════════════════════════════════════════════════════════════

export const getRandomExpression = (category: keyof typeof DIALOGS.venetian_expressions): string => {
  const expressions = DIALOGS.venetian_expressions[category]
  return expressions[Math.floor(Math.random() * expressions.length)]
}

// ═══════════════════════════════════════════════════════════════════════════
// NPC DIALOGUES BY CITY
// ═══════════════════════════════════════════════════════════════════════════

export const CITY_DIALOGS = {
  canalborgo: {
    fisherman: [
      'Sto pescando da 30 anni!',
      'I pesci de canalboro xe i migliori!',
      'Una volta ho vist un Bestia grandissimo!',
    ],
    tourist: [
      'Venezia xe tanto bela!',
      'I canali i ga propio ragion!',
      'El vaporetto xe in ritardo. Sempre.',
    ],
    shop_owner: [
      'Benvenuto nel mio store!',
      'Gli affari van mal, ma se sopravive!',
      'Proa el mio spritz, xe el pì buono!',
    ],
  },
  spritzia: {
    bartender: [
      'Bevi uno spritz!',
      'El spritz xe la vita!',
      'Senza spritz, no se pol vivar!',
    ],
    gondolier: [
      'Vogar no xe easy!',
      'El Canal Grande xe lunghissimo!',
      'Una volta gò portao un Doge!',
    ],
    gelataio: [
      'Gelato fresco!',
      'El gelato de Spritzia xe famoso!',
      'Semper in coda, ma ne capita!',
    ],
  },
  veronara: {
    opera_singer: [
      'LA VITA E\' UN OPERA!',
      'Vieni a sentir el mio concerto!',
      'Romeo e Giulietta? Quela xe de Verona!',
    ],
    pizza_maker: [
      'La pizza xe napoletana, ma la faccio alla veneta!',
      'Poca mozzarella, tanto osel!',
      'Un trancio? Xe sempre mejo!',
    ],
  },
  padoana: {
    student: [
      'Studio a Padoana!',
      'La Università xe la pì bella!',
      'Gò da dar 5 esami!',
    ],
    painter: [
      'Pingo come Tiziano!',
      'I colori i xe tuti nel mio studio!',
      'La mia Gioconda xe pì bella!',
    ],
  },
  trevisella: {
    farmer: [
      'La campagna xe bona!',
      'El radicchio xe el mio!',
      'La polenta xe sempre pronta!',
    ],
    winemaker: [
      'El vin xe bonissimo!',
      'Proa el mio prosecco!',
      'Un gotto e se parla!',
    ],
  },
  dolomax: {
    climber: [
      'Le Dolomiti xe le pì belle!',
      'El sole el pol far mal!',
      'Gò conquistao 50 cime!',
    ],
    shepherd: [
      'Le mie pecore xe content!',
      'El formaggio xe stagionao!',
      'La montagna xe casa mia!',
    ],
  },
  gardalago: {
    swimmer: [
      'El lago xe fredo!',
      'Una nuotada e son vivo!',
      'L\'acqua xe pì buona de la mare!',
    ],
    fisherman_lake: [
      'Qua i pesi i xe pì boni!',
      'El luccio xe grandissimo!',
      'El lago el ga i suoi secreti!',
    ],
  },
}

// ═══════════════════════════════════════════════════════════════════════════
// Random tips for the player
// ═══════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════
// DIALOGHI PER LE NUOVE LOCATION
// ═══════════════════════════════════════════════════════════════════════════

export const LOCATION_DIALOGS = {
  // VILLA VENETA
  villa_veneta: {
    nobildonna: [
      'Benvenuto nella mia villa!',
      'La mia famiglia ha 300 anni!',
      'Abbiamo 50 stanze!',
      'Ma ne usiamo solo 3...',
      'Il resto fa pulizia!',
    ],
    servitore: [
      'Posso offrirti qualcosa?',
      'Vino? Acqua? Spritz?',
      'La polenta? No, non la facciamo...',
      'È troppo plebea per noi!',
    ],
    tesori: [
      'Hai trovato il mio tesoro!',
      'Era di mio nonno!',
      'L\'ho perso 50 anni fa!',
      'E tu l\'hai trovato!',
      'Che fortunato! ...Che ladro!',
    ],
  },
  
  // MUSEO DEI BESTI
  museo_besti: {
    guida: [
      'Benvenuto nel Museo dei Besti!',
      'Abbiamo fossili antichi!',
      'E Besti estinti!',
      'E foto di Besti!',
      'E Besti finti!',
    ],
    studioso: [
      'I fossili raccontano storie antiche!',
      'Una volta c\'erano Besti giganti!',
      'Poi sono stati cancellati...',
      'Dalla storia! Non dalla polenta!',
      'Quella è immortale!',
    ],
    fossile: [
      'Hai trovato un fossile!',
      'Questo è antico!',
      'Forse contiene un Besti!',
      'Portalo al laboratorio!',
      'Quello segreto, ovviamente!',
    ],
  },
  
  // GROTTA SEGRETAA
  grotta_segreta: {
    speleologo: [
      'Ho trovato il segreto!',
      'La grotta nasconde un tesoro!',
      'Ma non ti lascerò passare!',
      '*si mette in posa*',
    ],
    guardiano: [
      'Il tesoro è mio!',
      'L\'ho trovato prima di te!',
      'Però... forse possiamo...',
      '...dividerlo?',
    ],
    tesori_grotta: [
      'Hai trovato il tesoro finale!',
      'È il Dogeball!',
      'Cattura qualsiasi Besti!',
      'Quasi qualsiasi!',
      'Forse no i leggendari!',
    ],
  },
  
  // TEMPIO ANTICO
  tempio_antico: {
    sacerdote: [
      'Il tempio nasconde segreti...',
      'Segreti antichi!',
      'Segreti del Doge!',
      'Segreti della polenta!',
    ],
    guardiano_sacro: [
      'Il tempio ti ha scelto!',
      'Solo i degni possono passare!',
      'Sei degno? ...Non so!',
      'Forse sì! Forse no!',
    ],
    tesori_tempio: [
      'Hai trovato il tesoro sacro!',
      'La Maschera del Doge!',
      'Questa maschera ha poteri...',
      '...di far sembrare te un Doge!',
      'Non proprio! È solo decorativa!',
    ],
  },
  
  // TORRE DI OSSERVAZIONE
  torre_osservazione: {
    guardiano: [
      'Questa torre ha una vista magnifica!',
      'Puoi vedere tutto Venetia!',
      'Ma oggi c\'è nebbia!',
      'Forse domani!',
    ],
    vista: [
      'Che vista!',
      'Quasi tutta la regione!',
      'Forse anche il Doge!',
      'Se è sul tetto!',
    ],
  },
  
  // LABORATORIO SEGRETAA
  lab_segreto: {
    scienziato: [
      'Benvenuto nel mio laboratorio!',
      'Sto creando il Besti perfetto!',
      'Con la polenta perfetta!',
      'Che non esiste ancora!',
    ],
    guardia_lab: [
      'NON DOVRESTI ESSERE QUI!',
      'Questo laboratorio è segreto!',
      '...Ora che ti ho detto...',
      '...devo combatterti!',
    ],
    segreti_lab: [
      'Hai trovato i miei segreti!',
      'Questo è il Dogeball!',
      'L\'ho creato io!',
      'O rubato! Non ricordo!',
    ],
  },
  
  // SPIAGGIA
  spiaggia: {
    bagnino: [
      'Acqua bella fresca!',
      'Solo 10 gradi!',
      'In estate!',
      'In inverno! ...Freddo!',
    ],
    pescatore_spiaggia: [
      'Qua i pesci i xe buoni!',
      'Ma i xe freddi!',
      'Come l\'acqua!',
    ],
  },
  
  // VILLA NONNO
  casa_nonno: {
    nonno: [
      'Nel mio tempo...',
      '...i Besti si chiamavano Bestie!',
      'E non c\'era ste palle!',
      'Si usava il cappello!',
      'E funzionava meglio!',
    ],
    ricetta: [
      'Hai trovato la Ricetta Segreta!',
      'È per lo spritz perfetto!',
      'Prosecco, Aperol, soda!',
      'E un pizzico di polenta!',
      '...Non era nella ricetta!',
      'L\'ho aggiunta io!',
    ],
  },
}

export const GAME_TIPS = [
  'Cattura molti Besti per il tuo BestiDex!',
  'I tipi Ghiaccio sono deboli contro Fuoco!',
  'Alcuni Besti evolvono usando le pietre!',
  'Vai al Centro Besti per curare i tuoi amici!',
  'I negozi vendono pozioni e capture balls!',
  'I Gym Leaders hanno Besti molto forti!',
  'La Squadra Polenta vuole dominare Venetia!',
  'Esplora tutte le citt\u00e0 per trovare NPC speciali!',
  'Alcuni oggetti sono nascosti nell\'erba alta!',
  'Il tuo rivale Marco è sempre pronto a combattere!',
  'I Besti leggendari sono molto rari!',
  'Usa le MT per insegnare mosse ai tuoi Besti!',
  'La Lega Elite Four richiede 6 Badge!',
  'La Bici Rubata ti fa muovere più velocemente!',
  'La Gondola d\'Oro ti porta ovunque in Venetia!',
  'Il radicchio dorato può guarire qualsiasi status!',
  'Ogni Gym ha un tema diverso - studia i tipi!',
  'Marco è tuo fratello - la famiglia è importante!',
  'Il Dux Polenta non è cattivo, solo triste!',
  'La compassione può salvare più della forza!',
  'Le Ville Venete hanno 3 piani da esplorare!',
  'I Templi Antichi nascondono tesori leggendari!',
  'Le Grotte Segrete hanno 3 livelli di sfide!',
  'Le Torri di Osservazione offrono viste mozzafiato!',
  'Il Dogeball cattura sempre - rarissimo!',
  'Il Carnevaleball è il più raro di tutti!',
  'Le Pietre di Evoluzione cambiano per sempre i tuoi Besti!',
  'La Pietra Alba e Tramonto sono molto rare!',
  'La Pietra Drago è per i Besti più potenti!',
  'Alcuni Besti evolvono solo di notte!',
  'I Besti Ombra sono i più misteriosi!',
  'I Besti Drago sono rarissimi e fortissimi!',
  'Esplora i Musei per trovare fossili antichi!',
  'I Laboratori Segreti nascondono esperimenti!',
  'I Sacerdoti nei Templi benedicono i tuoi Besti!',
  'Gli Speleologi nelle Grotte cercano tesori!',
  'I Nonni hanno sempre storie da raccontare!',
  'I Bambini chiedono sempre di vedere i tuoi Besti!',
  'I Turisti vogliono sempre foto e ricordi!',
  'I Bambini piangono se non mostri i tuoi Besti!',
  'I Tifosi parlano solo di calcio e Besti!',
  'Gli Zii chiedono sempre quando ti sposi!',
  'I Nonni danno sempre consigli non richiesti!',
  'Gli Youtuber vogliono fare video con te!',
  'Gli Attivisti vogliono liberare i Besti!',
  'I Poliziotti multano tutti, anche i Besti!',
  'I Ladri cercano di rubare i tuoi oggetti!',
  'I Complottisti credono a tutto!',
  'I Filosofici parlano sempre del senso della vita!',
]

// ═══════════════════════════════════════════════════════════════════════════
// PERSONAGGI FASTIDIOSI EXTRA - Per rendere il gioco più vivo
// ═══════════════════════════════════════════════════════════════════════════

export const ANNOYING_CHARACTERS = {
  // MARANZA
  maranzo: [
    'Maranzo de Milano!',
    'Xe el pì figo de Canalborgo!',
    'La mia Vespa? Modificata!',
    'Le ragazze? Tutte per mi!',
    'Lo so, son invidiabile!',
  ],
  sgarbo_milanese: [
    'SONO DI MILANO!',
    'LA LOMBARDIA È SUPERIORE!',
    'I veneti? Campagnoli!',
    'Il risotto? Con lo zafferano, ovvio!',
    'Il polentone? Roba da poveri!',
  ],
  raffaele: [
    'Raffaele! El pì bello!',
    'Le donne mi corrono dietro!',
    'I soldi? Ne ho tanti!',
    'La vita? Bellissima!',
    'Tranne oggi che ho perso il treno...',
  ],
  chicco: [
    'Chicco! Chicco!',
    'Lo so che sono Chicco!',
    'Non lo dimenticherò mai!',
    'Chicco Chicco Chicco!',
    'Che confusione! Ma che bella!',
  ],

  // TERRONI
  salvatore_napoli: [
    'So\' Salvatore! De Napoli!',
    'Pizza? Sempe fresca!',
    ' Maradona? Dio!',
    'Napoli è superiore a tutto!',
    'Ma Venecia? Bella, dai!',
  ],
  carmelo_catania: [
    'Carmelo! Sono catanese!',
    'Il cannolo? Specialità!',
    'L\'Etna? Mia!',
    'Il calcio? Solo Catania!',
    'Ma lo spritz? Buono anche qui!',
  ],
  giuseppe_palermo: [
    'Giuseppe! Palermitano!',
    'La cassata? Unici al mondo!',
    'Palermo è meglio di Milano!',
    'I canali? Anche noi li abbiamo!',
    'Ma più puzzano...',
  ],
  pasquale_bari: [
    'Pasquale! Di BARI!',
    'Il polpo? Freschissimo!',
    'Bari è la città migliore!',
    'Il mare? Chiaro!',
    'Le polpette? Divinis!',
  ],
  michele: [
    'Michele! Sono Michele!',
    'Parlo sempre di me!',
    'Michele Michele Michele!',
    'Lo so, sono egocentrico!',
    'Ma chi se ne frega!',
  ],
  luigi_roma: [
    'Luigi! Romano de Roma!',
    'La carbonara? Vera!',
    'Il Colosseo? Bellissimo!',
    'La Vespa? Mia!',
    'Ma Venezia? Pure bella!',
  ],
  marco_ostia: [
    'Marco! De Ostia!',
    'Il pesce? PESCATO DA ME!',
    'Il beach? Il mio!',
    'Ostia è meglio di tutto!',
    'Tranne quando c\'è scirocco...',
  ],

  // ROMPIPALLE
  commentatore_calabrese: [
    'MA CHE BELLO! CHE FORMA!',
    'Guarda che rovesciata!',
    'INCRE-DIBILE!',
    'Il migliore del mondo!',
    'Parole parole parole...',
  ],
  filosofo_torinese: [
    'Esiste il tempo? O esiste solo lo spazio?',
    'E se il tempo fosse una palla di polenta?',
    'La risposta è dentro di te!',
    'O forse fuori! Chi lo sa!',
    'La filosofia non ha risposte!',
  ],
  pettegola_veneta: [
    'Lo sai chi è stato?',
    'TE LO DICO IO!',
    'È stato quello! Con quell\'altro!',
    'E la moglie? Poverina!',
    'Ma non dirgli che te l\'ho detto!',
  ],
  chiacchierone: [
    'Allora, come ti dicevo...',
    'Dove ero? Ah sì!',
    'C\'era una volta...',
    'E poi... e poi...',
    'FACCIAMO 3 ORE ANCORA!',
  ],
  storico: [
    'Nel 1400 successe che...',
    'Aspetta, nel 1300!',
    'No, aspetta, nel 1500!',
    'Cazzo, mi sono perso!',
    'Ricominciamo da Carlo Magno!',
  ],
  complottista: [
    'I Besti sono tutti creati dal governo!',
    'Il Doge era un alieno!',
    'La polenta? Segreto militare!',
    'L\'acqua? Troppo bagnata!',
    'TUTTO È SOSPETTO!',
  ],
  mago: [
    'ABRACADABRA!',
    'Guarda! Niente!',
    'Ho perso la bacchetta...',
    'Ma la magia è nel cuore!',
    'ANCHE NEL TUO! ...Forse!',
  ],
  guaritore: [
    'Ho l\'acqua santa!',
    'Cur tutto con le mani!',
    'La polenta?Medicina!',
    'Lo spritz? Pure!',
    'Siediti, ti curo!',
  ],
  psicologo: [
    'E come ti senti?',
    'Parlami della tua infanzia!',
    'I tuoi genitori... racconta!',
    'E la polenta? Cosa rappresenta?',
    'FAMMI 50 SEDUTE!',
  ],
  barista_filosofo: [
    'Che caffè vuoi?',
    'Non il caffè! LA VITA!',
    'Amaro o dolce?',
    'Come l\'esistenza!',
    'Un altro? SEMPRE!',
  ],
  suonatore: [
    'TIRO FUORI LA MUSICA!',
    '*suona una nota stonata*',
    'Era intenzionale!',
    'La musica è nell\'aria!',
    'E pure la stonatura!',
  ],
  casalinga: [
    'Ho 8 figli!',
    'E 15 nipoti!',
    'E 40 Besti!',
    'E una casa sempre in disordine!',
    'MA CHE BELLA VITA!',
  ],
  fashion_victim: [
    'Questo vestito? Di Parigi!',
    'Queste scarpe? Di Milano!',
    'Questa borsa? Di Venezia!',
    'Questo colore? Di moda!',
    'MA I SOLDI? FINITI!',
  ],
  gossiparo: [
    'Hai sentito di quello che...',
    'NON È VERO! MA SI DICE!',
    'E poi la moglie di...',
    'E il figlio di...',
    'MA È TUTTO CHIACCHIERE!',
  ],

  // VENDITORI
  porta_a_porta: [
    'Compro! Vendo! Tutto!',
    'Un affare! Un AFFARE!',
    'Questo orologio? 1000€!',
    'È falso, ma chi se ne frega!',
    'COMPRO ANCHE LA TUA CASA!',
  ],
  venditore_profumi: [
    'Profumo! Profumo di Venetia!',
    'Con essenza di polenta!',
    'E spritz!',
    'Solo 50€! Un affare!',
    'Puzza? No, è il profumo!',
  ],
  venditore_calzini: [
    'CALZINI! CALZINI BUONI!',
    'In lana! In cotone!',
    'Con i buchi dentro!',
    'Solo 2€!',
    'Ma ti servono 2 paia!',
  ],
  venditore_spazzole: [
    'Spazzole! Per capelli!',
    'Per denti! Per casa!',
    'Per Besti! Per pavimenti!',
    'TUTTO È SPOLVERE!',
    'MA CON LE MIE SPAZZOLE!',
  ],
  venditore_enciclopedie: [
    'Enciclopedia! Completa!',
    '100 volumi!',
    'Solo 500€!',
    'Ma chi legge più?',
    'È un investimento!',
  ],
  venditore_integratori: [
    'Integratori! Per muscoli!',
    'Per memoria! Per sonno!',
    'Per fame! Per sete!',
    'Per vivere! Per morire!',
    'Solo 30€ OGNI UNO!',
  ],

  // ANIMALISTI/ATTIVISTI
  attivista_animale: [
    'I BESTI SONO LIBERI!',
    'LIBERTÀ PER TUTTI!',
    'LA POLENTA È UN CRIMINE!',
    'LIBERATE I GABBIANI!',
    'I CANALI SONO PRIGIONI!',
  ],
  ambientalista: [
    'IL PIANETA STA MORENDO!',
    'I CANALI SONO INQUINATI!',
    'LA POLENTA È UN CRIMINE AMBIENTALE!',
    'PIANTATE ALBERI!',
    'E VIAGGIATE MENO!',
  ],

  // NONNI
  nonna_credula: [
    'NEL MIO TEMPO ERA MEGLIO!',
    'I Besti? Più forti!',
    'La polenta? Più buona!',
    'I giovani? Più rispettosi!',
    'TUTTO ERA MEGLIO!',
  ],
  nonna_pettegola: [
    'LO SAI DI MARIA?',
    'E DI GIUSEPPE?',
    'E DEL CANE DI GINO?',
    'TUTTI I SEGRETI!',
    'CHE NESSUNO SA!',
  ],
  nonno_storie: [
    'TE LO DICO IO!',
    'UNA VOLTA...',
    'C\'ERA UNA VOLTA...',
    'QUANDO ERO GIOVANE...',
    'FAMMI RICOMINCIARE!',
  ],
  nonna_preoccupata: [
    'ATTENTO!',
    'NON FIDARTI!',
    'I PERICOLI!',
    'DOVE VAI?',
    'MI PREOCCUPO!',
  ],
  nonno_mangione: [
    'HO FAMEEEE!',
    'La polenta? Un\'altra!',
    'Il risotto? Pure!',
    'Lo spritz? Naturalmente!',
    'SONO SEMPRE AFFAMATO!',
  ],

  // BAMBINI
  capriccio: [
    'VOGLIO! VOGLIO! VOGLIO!',
    'IL BESTIA! QUELLO VERDE!',
    'NO! QUELLO BLU!',
    'TUTTI! VOGLIO TUTTI!',
    '*piange*',
  ],
  cinquecento_domande: [
    'Perché?',
    'E perché?',
    'E poi perché?',
    'E ancora perché?',
    'E INFINITAMENTE PERCHÉ?',
  ],
  gambero: [
    'SCAPPO!',
    '*inciampa*',
    '*cade*',
    '*piange*',
    '*scappa di nuovo*',
  ],

  // TIFOSI
  tifoso_juve: [
    'FORZA JUVE!',
    'SEMPRE FORZA!',
    'La Serie A è nostra!',
    'Champions? Prossimo anno!',
    'MA INTANTO... FORZA JUVE!',
  ],
  tifoso_milan: [
    'FORZA MILAN!',
    'I ROSSONERI!',
    'La storia è dalla nostra!',
    'I derby? Li vinciamo noi!',
    'SEMPRE FORZA MILAN!',
  ],
  tifoso_inter: [
    'FORZA INTER!',
    'IL BIScione!',
    'Champions? Due volte!',
    'La Serie A? Pure!',
    'SEMPRE FORZA INTER!',
  ],
  tifoso_napoli: [
    'FORZA NAPOLI!',
    'MARADONA È DIO!',
    'Il gol? Infinito!',
    'Il mare? Azzurro!',
    'SEMPRE FORZA NAPoli!',
  ],
  tifoso_roma: [
    'FORZA ROMA!',
    'LA LUPA!',
    'Il Colosseo? Tifo!',
    'I tifosi? Passionali!',
    'SEMPRE FORZA ROMA!',
  ],
  tifoso_lazio: [
    'FORZA LAZIO!',
    'LE AQUILE!',
    'La città? Divisione!',
    'Il derby? Guerrafredda!',
    'SEMPRE FORZA LAZIO!',
  ],

  // ZII E PARENTI FASTIDIOSI
  zio_imbarazzante: [
    'SEI GRASSO!',
    'SEI MAGRO!',
    'MANGIA DI PIÙ!',
    'MANGIA DI MENO!',
    'QUANDO TI SPOSI?!',
  ],
  zia_impicciona: [
    'QUANTO GUADAGNI?',
    'DOVE VIVI?',
    'CON CHI VIVI?',
    'E I Soldi?',
    'TUTTO! VOGLIO SAPERE TUTTO!',
  ],
  zia_approfonditrice: [
    'MA COSA SIGNIFICA?',
    'SPiegami meglio!',
    'E ANCORA!',
    'E ANCORA ANCORA!',
    'NON CAPISCO MAI!',
  ],
  zio_curioso: [
    'MA TU SAI CHI È...?',
    'E COSA FA...?',
    'E DOVE VA...?',
    'QUANDO TORNA...?',
    'TUTTO QUELLO CHE VUOI SAPERE!',
  ],

  // LADRI
  ladro_cioccolatini: [
    'Cioccolatini! Caldi!',
    '*distrae*',
    '*ruba*',
    '*scappa*',
    '*si nasconde*',
  ],
  ladro_sogni: [
    'I tuoi sogni? RUBATI!',
    'Le speranze? PURÈ!',
    'I desideri? TUTTI!',
    'Tranne la polenta!',
    'QUELLA È PESANTE!',
  ],

  // POLIZIA
  vigile_ossessivo: [
    'ALTO! DOCUMENTI!',
    'La luce? Gialla!',
    'Il semaforo? Rosso!',
    'La multa? 500€!',
    'MA È SEMPRE COLPA TUA!',
  ],

  // YOUTUBER
  youtuber_molesto: [
    'CIAO A TUTTI!',
    'ISCRIVETIVI!',
    'LIKE! COMMENT! SUBSCRIBE!',
    'QUESTO È UN VIDEO!',
    'SIAMO IN UN VIDEOGIOCO!',
    'NON È REALE!',
    'MA È BELLO LO STESSO!',
    'ANCORA UNA COSA!',
    'E UN\'ALTRA!',
    'E UN\'ALTRA ANCORA!',
    'FINE! O FORSE NO!',
    'CIAO!',
  ],
}

// Get a random game tip
export const getRandomTip = (): string => {
  return GAME_TIPS[Math.floor(Math.random() * GAME_TIPS.length)]
}
