// Items System - Venetian themed items
export type ItemType = 'capture' | 'heal' | 'stone' | 'key' | 'tm' | 'food' | 'vehicle' | 'battle' | 'hold'

export interface GameItem {
  id: string
  name: string
  desc: string
  type: ItemType
  price: number
  val?: number
  effect?: string
  sprite?: string
}

export const ITEMS: Record<string, GameItem> = {
  // ═══════════════════════════════════════════════════════════════════
  // VENETIAN POKEBALLS - 12 balls for different situations
  // ═══════════════════════════════════════════════════════════════════
  
  // BASIC BALLS
  gondolball: {
    id: 'gondolball',
    name: 'Gondolball',
    desc: 'Palla speciale a forma di gondola. Standard.',
    type: 'capture',
    price: 200,
    effect: 'standard',
    sprite: 'gondola',
  },
  mascheraball: {
    id: 'mascheraball',
    name: 'Mascheraball',
    desc: 'Palla del carnevale. Efficace su Besti notturni.',
    type: 'capture',
    price: 300,
    effect: 'night_bonus',
    sprite: 'maschera',
  },
  
  // SPECIALTY BALLS
  spritzball: {
    id: 'spritzball',
    name: 'Spritzball',
    desc: 'Palla frizzante! Efficace al tramonto.',
    type: 'capture',
    price: 400,
    effect: 'dusk_bonus',
    sprite: 'spritz',
  },
  polentaball: {
    id: 'polentaball',
    name: 'Polentaball',
    desc: 'Palla pesante. Migliore su Besti forti.',
    type: 'capture',
    price: 600,
    effect: 'strong_bonus',
    sprite: 'polenta',
  },
  scampaball: {
    id: 'scampaball',
    name: 'Scampaball',
    desc: 'Palla luccicante. Migliore su Besti acquatici.',
    type: 'capture',
    price: 500,
    effect: 'water_bonus',
    sprite: 'scampi',
  },
  vinoball: {
    id: 'vinoball',
    name: 'Vinoball',
    desc: 'Palla rossastra. Per Besti Terra.',
    type: 'capture',
    price: 500,
    effect: 'earth_bonus',
    sprite: 'vino',
  },
  lagunaball: {
    id: 'lagunaball',
    name: 'Lagunaball',
    desc: 'Palla azzurra. Migliore nelle zone acqua.',
    type: 'capture',
    price: 600,
    effect: 'water_zone_bonus',
    sprite: 'laguna',
  },
  montagnaball: {
    id: 'montagnaball',
    name: 'Montagnaball',
    desc: 'Palla delle Dolomiti. Per Besti Ice.',
    type: 'capture',
    price: 600,
    effect: 'ice_bonus',
    sprite: 'montagna',
  },
  aereoball: {
    id: 'aereoball',
    name: 'Aereoball',
    desc: 'Palla leggera. Per Besti Air.',
    type: 'capture',
    price: 500,
    effect: 'air_bonus',
    sprite: 'aereo',
  },
  
  // RARE BALLS
  graticciaball: {
    id: 'graticciaball',
    name: 'Graticciaball',
    desc: 'Palla delle maschere. Per Besti Magic.',
    type: 'capture',
    price: 800,
    effect: 'magic_bonus',
    sprite: 'graticcia',
  },
  serenaball: {
    id: 'serenaball',
    name: 'Serenaball',
    desc: 'Palla della serenata. Per Besti Psycho.',
    type: 'capture',
    price: 800,
    effect: 'psycho_bonus',
    sprite: 'serena',
  },
  dragoball: {
    id: 'dragoball',
    name: 'Dragoball',
    desc: 'Palla del Drago. Solo per Besti Drago!',
    type: 'capture',
    price: 1000,
    effect: 'dragon_bonus',
    sprite: 'drago',
  },
  ultraball: {
    id: 'ultraball',
    name: 'Ultra Ball',
    desc: 'Palla ad alte prestazioni. Migliore della Gondolball standard.',
    type: 'capture',
    price: 800,
    effect: 'high_capture',
    sprite: 'ultra_ball',
  },
  
  // ULTRA RARE BALLS
  dogeball: {
    id: 'dogeball',
    name: 'Dogeball',
    desc: 'Palla dorata del Doge! Cattura garantita!',
    type: 'capture',
    price: 0,
    effect: 'guaranteed_capture',
    sprite: 'doge',
  },
  carnevaleball: {
    id: 'carnevaleball',
    name: 'Carnevaleball',
    desc: 'Palla arcobaleno del carnevale! Leggendaria!',
    type: 'capture',
    price: 0,
    effect: 'legendary_bonus',
    sprite: 'carnevale',
  },
  fantasmaball: {
    id: 'fantasmaball',
    name: 'Fantasma Ball',
    desc: 'Palla eterea. Per Besti Ombra.',
    type: 'capture',
    price: 700,
    effect: 'shadow_bonus',
    sprite: 'fantasma',
  },

  // ═══════════════════════════════════════════════════════════════════
  // MEDICINE & RECOVERY ITEMS
  // ═══════════════════════════════════════════════════════════════════
  
  pozioncino: {
    id: 'pozioncino',
    name: 'Pozioncino',
    desc: 'Rimedio economico. +20 PS.',
    type: 'heal',
    price: 100,
    val: 20,
    sprite: 'potion',
  },
  superpozione: {
    id: 'superpozione',
    name: 'Super Pozione',
    desc: 'Pozione migliore. +50 PS.',
    type: 'heal',
    price: 250,
    val: 50,
    sprite: 'super_potion',
  },
  iperpozione: {
    id: 'iperpozione',
    name: 'Iper Pozione',
    desc: 'Pozione potentissima! +100 PS.',
    type: 'heal',
    price: 500,
    val: 100,
    sprite: 'hyper_potion',
  },
  maxpozione: {
    id: 'maxpozione',
    name: 'Max Pozione',
    desc: 'Cura completamente i PS!',
    type: 'heal',
    price: 1200,
    val: 999,
    effect: 'full_heal_single',
    sprite: 'max_potion',
  },
  
  // VENETIAN FOOD & DRINKS
  spritz_curativo: {
    id: 'spritz_curativo',
    name: 'Spritz Curativo',
    desc: 'Aperitivo che ristora. +30 PS.',
    type: 'heal',
    price: 150,
    val: 30,
    sprite: 'spritz_heal',
  },
  caffette: {
    id: 'caffette',
    name: 'Caffè Corretto',
    desc: 'Caffè con grappa. +10 PS a tutto il gruppo.',
    type: 'heal',
    price: 80,
    val: 10,
    effect: 'party_heal_10',
    sprite: 'caffe',
  },
  cicchetto: {
    id: 'cicchetto',
    name: 'Cicchetto',
    desc: 'Spruzzo di grappa. +1 livello a un Bestia casuale!',
    type: 'food',
    price: 500,
    effect: 'random_level_up',
    sprite: 'cicchetto',
  },
  paninoVeneto: {
    id: 'paninoVeneto',
    name: 'Panino Veneto',
    desc: 'Panino con sopressa. Cura tutti i PS.',
    type: 'food',
    price: 300,
    val: 999,
    effect: 'full_heal',
    sprite: 'panino',
  },
  tagliatelle: {
    id: 'tagliatelle',
    name: 'Tagliatelle della Nonna',
    desc: 'Piatto della domenica. +50 PS a tutti.',
    type: 'food',
    price: 400,
    val: 50,
    effect: 'party_heal_50',
    sprite: 'pasta',
  },
  frittura_mista: {
    id: 'frittura_mista',
    name: 'Frittura Mista',
    desc: 'Pesce fritto veneto. +100 PS a tutti!',
    type: 'food',
    price: 600,
    val: 100,
    effect: 'party_heal_100',
    sprite: 'frittura',
  },
  grappa_medicinale: {
    id: 'grappa_medicinale',
    name: 'Grappa Medicinale',
    desc: 'Grappa forte. +20 PS e +5 Atk.',
    type: 'heal',
    price: 200,
    val: 20,
    effect: 'heal_and_buff',
    sprite: 'grappa',
  },
  
  // STATUS CURES
  acqua_sanita: {
    id: 'acqua_sanita',
    name: 'Acqua Santa',
    desc: 'Cura paralisi.',
    type: 'heal',
    price: 100,
    effect: 'cure_paralysis',
    sprite: 'acqua',
  },
  profumo_veneto: {
    id: 'profumo_veneto',
    name: 'Profumo Veneto',
    desc: 'Cura avvelenamento.',
    type: 'heal',
    price: 100,
    effect: 'cure_poison',
    sprite: 'profumo',
  },
  incenso_pace: {
    id: 'incenso_pace',
    name: 'Incenso della Pace',
    desc: 'Cura confusione.',
    type: 'heal',
    price: 100,
    effect: 'cure_confusion',
    sprite: 'incenso',
  },
  sonnifero: {
    id: 'sonnifero',
    name: 'Sonnifero Forte',
    desc: 'Cura sonno.',
    type: 'heal',
    price: 100,
    effect: 'cure_sleep',
    sprite: 'sonno',
  },
  acqua_benedetta: {
    id: 'acqua_benedetta',
    name: 'Acqua Benedetta',
    desc: 'Cura tutti i problemi di stato.',
    type: 'heal',
    price: 300,
    effect: 'cure_all_status',
    sprite: 'benedetta',
  },
  revive: {
    id: 'revive',
    name: 'Revitalizzante',
    desc: 'Rianima un Bestia sconfitto. 50% PS.',
    type: 'heal',
    price: 800,
    effect: 'revive',
    sprite: 'revive',
  },
  maxrevive: {
    id: 'maxrevive',
    name: 'Mega Revitalizzante',
    desc: 'Rianima un Bestia sconfitto. PS pieni!',
    type: 'heal',
    price: 2000,
    effect: 'revive_full',
    sprite: 'max_revive',
  },

  // ═══════════════════════════════════════════════════════════════════
  // EVOLUTION STONES - 15 stones for different evolutions
  // ═══════════════════════════════════════════════════════════════════
  
  // ELEMENTAL STONES
  pietra_focaia: {
    id: 'pietra_focaia',
    name: 'Pietra Focaia',
    desc: 'Pietra infuocata. Per Besti Fuoco.',
    type: 'stone',
    price: 800,
    effect: 'fire_evo',
    sprite: 'fire_stone',
  },
  pietra_acquatica: {
    id: 'pietra_acquatica',
    name: 'Pietra Acquatica',
    desc: 'Pietra marina. Per Besti Acqua.',
    type: 'stone',
    price: 800,
    effect: 'water_evo',
    sprite: 'water_stone',
  },
  pietra_tuono: {
    id: 'pietra_tuono',
    name: 'Pietra Tuono',
    desc: 'Pietra elettrica. Per Besti Electric.',
    type: 'stone',
    price: 800,
    effect: 'electric_evo',
    sprite: 'thunder_stone',
  },
  pietra_verde: {
    id: 'pietra_verde',
    name: 'Pietra Verde',
    desc: 'Pietra delle Dolomiti. Per Besti Natura.',
    type: 'stone',
    price: 800,
    effect: 'nature_evo',
    sprite: 'nature_stone',
  },
  pietra_ghiaccio: {
    id: 'pietra_ghiaccio',
    name: 'Pietra Ghiaccio',
    desc: 'Pietra gelida. Per Besti Ice.',
    type: 'stone',
    price: 900,
    effect: 'ice_evo',
    sprite: 'ice_stone',
  },
  pietra_terra: {
    id: 'pietra_terra',
    name: 'Pietra Terra',
    desc: 'Pietra pesante. Per Besti Terra.',
    type: 'stone',
    price: 900,
    effect: 'earth_evo',
    sprite: 'earth_stone',
  },
  
  // SPECIAL STONES
  pietra_luna: {
    id: 'pietra_luna',
    name: 'Pietra Luna',
    desc: 'Pietra lunare. Per Besti notturni.',
    type: 'stone',
    price: 1000,
    effect: 'moon_evo',
    sprite: 'moon_stone',
  },
  pietra_sole: {
    id: 'pietra_sole',
    name: 'Pietra Sole',
    desc: 'Pietra solare. Per Besti diurni.',
    type: 'stone',
    price: 1000,
    effect: 'sun_evo',
    sprite: 'sun_stone',
  },
  pietra_alba: {
    id: 'pietra_alba',
    name: 'Pietra Alba',
    desc: 'Pietra dell\'alba. Evoluzione speciale.',
    type: 'stone',
    price: 1000,
    effect: 'dawn_evo',
    sprite: 'dawn_stone',
  },
  pietra_tramonto: {
    id: 'pietra_tramonto',
    name: 'Pietra Tramonto',
    desc: 'Pietra del tramonto. Evoluzione speciale.',
    type: 'stone',
    price: 1000,
    effect: 'dusk_evo',
    sprite: 'dusk_stone',
  },
  pietra_fulmine: {
    id: 'pietra_fulmine',
    name: 'Pietra Fulmine',
    desc: 'Pietra scintillante. Per Besti Psycho.',
    type: 'stone',
    price: 1000,
    effect: 'shiny_evo',
    sprite: 'shiny_stone',
  },
  
  // VENETIAN THEMED STONES
  pietra_temporale: {
    id: 'pietra_temporale',
    name: 'Pietra Temporale',
    desc: 'Pietra antica. Per Besti Air/Psycho.',
    type: 'stone',
    price: 1000,
    effect: 'air_evo',
    sprite: 'air_stone',
  },
  pietra_polenta: {
    id: 'pietra_polenta',
    name: 'Pietra Polenta',
    desc: 'Pietra dorata. Per Besti Terra.',
    type: 'stone',
    price: 1000,
    effect: 'earth_evo',
    sprite: 'earth_stone',
  },
  pietra_maschera: {
    id: 'pietra_maschera',
    name: 'Pietra Maschera',
    desc: 'Pietra del carnevale. Per Besti Magic.',
    type: 'stone',
    price: 1200,
    effect: 'magic_evo',
    sprite: 'magic_stone',
  },
  pietra_ombra: {
    id: 'pietra_ombra',
    name: 'Pietra Ombra',
    desc: 'Pietra oscura. Per Besti Ombra.',
    type: 'stone',
    price: 1200,
    effect: 'shadow_evo',
    sprite: 'shadow_stone',
  },
  pietra_drago: {
    id: 'pietra_drago',
    name: 'Pietra Drago',
    desc: 'Pietra leggendaria. Per Besti Drago.',
    type: 'stone',
    price: 2000,
    effect: 'dragon_evo',
    sprite: 'dragon_stone',
  },

  // ═══════════════════════════════════════════════════════════════════
  // KEY ITEMS - Story & Progression
  // ═══════════════════════════════════════════════════════════════════
  
  biglietto_treno: {
    id: 'biglietto_treno',
    name: 'Biglietto Treno',
    desc: 'Per viaggiare tra le città.',
    type: 'key',
    price: 0,
    effect: 'travel',
    sprite: 'ticket',
  },
  scooterino: {
    id: 'scooterino',
    name: 'Scooterino',
    desc: 'Motorino per muoverti velocemente!',
    type: 'vehicle',
    price: 5000,
    effect: 'fast_travel',
    sprite: 'scooter',
  },
  biciRubata: {
    id: 'biciRubata',
    name: 'Bici Rubata',
    desc: 'Bici rubata dal cugino. +velocità.',
    type: 'vehicle',
    price: 0,
    effect: 'speed_up',
    sprite: 'bike',
  },
  barchino: {
    id: 'barchino',
    name: 'Barchino',
    desc: 'Barchino per attraversare i canali!',
    type: 'vehicle',
    price: 0,
    effect: 'water_travel',
    sprite: 'boat',
  },
  gondola_oro: {
    id: 'gondola_oro',
    name: 'Gondola d\'Oro',
    desc: 'Gondola del Doge. Surf sui canali!',
    type: 'vehicle',
    price: 0,
    effect: 'water_surf',
    sprite: 'gondola_gold',
  },
  chiavi_casa: {
    id: 'chiavi_casa',
    name: 'Chiavi di Casa',
    desc: 'Le chiavi di casa tua.',
    type: 'key',
    price: 0,
    effect: 'home_tp',
    sprite: 'keys',
  },
  pacco_sospetto: {
    id: 'pacco_sospetto',
    name: 'Pacco Sospetto',
    desc: 'Da consegnare a Veronara.',
    type: 'key',
    price: 0,
    effect: 'story_pacco',
    sprite: 'package',
  },
  mantello_polenta: {
    id: 'mantello_polenta',
    name: 'Mantello Polenta',
    desc: 'Il mantello della Compagnia!',
    type: 'key',
    price: 0,
    effect: 'story_mantello',
    sprite: 'cloak',
  },
  
  // STORY KEY ITEMS
  diario_doge: {
    id: 'diario_doge',
    name: 'Diario del Doge',
    desc: 'Diario antico con segreti.',
    type: 'key',
    price: 0,
    effect: 'story_diario',
    sprite: 'diario',
  },
  maschera_doge: {
    id: 'maschera_doge',
    name: 'Maschera del Doge',
    desc: 'La maschera dorata del Doge.',
    type: 'key',
    price: 0,
    effect: 'story_maschera',
    sprite: 'maschera_doge',
  },
  anello_doge: {
    id: 'anello_doge',
    name: 'Anello del Doge',
    desc: 'L\'anello del Doge. Potere antico.',
    type: 'key',
    price: 0,
    effect: 'story_anello',
    sprite: 'anello',
  },
  mappa_antica: {
    id: 'mappa_antica',
    name: 'Mappa Antica',
    desc: 'Mappa che mostra luoghi nascosti.',
    type: 'key',
    price: 0,
    effect: 'reveal_secrets',
    sprite: 'mappa',
  },
  chiave_segreta: {
    id: 'chiave_segreta',
    name: 'Chiave Segreta',
    desc: 'Apre porte nascoste.',
    type: 'key',
    price: 0,
    effect: 'open_secret_doors',
    sprite: 'chiave',
  },
  fossile_uovo: {
    id: 'fossile_uovo',
    name: 'Fossile Uovo',
    desc: 'Uovo fossile da far schiudere.',
    type: 'key',
    price: 0,
    effect: 'hatch_fossil',
    sprite: 'fossile',
  },
  piuma_verde: {
    id: 'piuma_verde',
    name: 'Piuma Verde',
    desc: 'Piuma rara di uccello veneto.',
    type: 'key',
    price: 0,
    effect: 'story_piuma',
    sprite: 'piuma',
  },
  lettera_amore: {
    id: 'lettera_amore',
    name: 'Lettera d\'Amore',
    desc: 'Lettera di un innamorato segreto.',
    type: 'key',
    price: 0,
    effect: 'story_lettera',
    sprite: 'lettera',
  },
  amuleto_veneto: {
    id: 'amuleto_veneto',
    name: 'Amuleto Veneto',
    desc: 'Protegge da maledizioni.',
    type: 'key',
    price: 0,
    effect: 'protection',
    sprite: 'amuleto',
  },

  // ═══════════════════════════════════════════════════════════════════
  // TMs (Tecniche Mascherate) - 50 TMs
  // ═══════════════════════════════════════════════════════════════════
  
  // NORMAL TMs
  tm_brusco: {
    id: 'tm_brusco',
    name: 'TM Brusc',
    desc: 'Insegna: Brusc - attacco normale.',
    type: 'tm',
    price: 3000,
    effect: 'tm_brusco',
    sprite: 'tm',
  },
  tm_colpo: {
    id: 'tm_colpo',
    name: 'TM Colpo',
    desc: 'Insegna: Colpo - attacco normale.',
    type: 'tm',
    price: 3000,
    effect: 'tm_colpo',
    sprite: 'tm',
  },
  
  // FIRE TMs
  tm_fuocartto: {
    id: 'tm_fuocartto',
    name: 'TM Fuocartto',
    desc: 'Insegna: Fuocartto - attacco Fuoco forte.',
    type: 'tm',
    price: 4000,
    effect: 'tm_fuocartto',
    sprite: 'tm_fire',
  },
  tm_inferno: {
    id: 'tm_inferno',
    name: 'TM Inferno',
    desc: 'Insegna: Inferno - attacco Fuoco devastante.',
    type: 'tm',
    price: 6000,
    effect: 'tm_inferno',
    sprite: 'tm_fire',
  },
  
  // WATER TMs
  tm_ondata: {
    id: 'tm_ondata',
    name: 'TM Ondata',
    desc: 'Insegna: Ondata - attacco Acqua.',
    type: 'tm',
    price: 4000,
    effect: 'tm_ondata',
    sprite: 'tm_water',
  },
  tm_tsunami: {
    id: 'tm_tsunami',
    name: 'TM Tsunami',
    desc: 'Insegna: Tsunami - attacco Acqua devastante.',
    type: 'tm',
    price: 6000,
    effect: 'tm_tsunami',
    sprite: 'tm_water',
  },
  
  // ELECTRIC TMs
  tm_scossa: {
    id: 'tm_scossa',
    name: 'TM Scossa',
    desc: 'Insegna: Scossa - attacco Electric.',
    type: 'tm',
    price: 4000,
    effect: 'tm_scossa',
    sprite: 'tm_electric',
  },
  tm_fulmine: {
    id: 'tm_fulmine',
    name: 'TM Fulmine',
    desc: 'Insegna: Fulmine - attacco Electric forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_fulmine',
    sprite: 'tm_electric',
  },
  
  // NATURE TMs
  tm_erba_alta: {
    id: 'tm_erba_alta',
    name: 'TM Erba Alta',
    desc: 'Insegna: Erba Alta - attacco Natura.',
    type: 'tm',
    price: 4000,
    effect: 'tm_erbaalta',
    sprite: 'tm_nature',
  },
  tm_tempesta: {
    id: 'tm_tempesta',
    name: 'TM Tempesta',
    desc: 'Insegna: Tempesta - attacco Natura forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_tempesta',
    sprite: 'tm_nature',
  },
  
  // ICE TMs
  tm_gelartto: {
    id: 'tm_gelartto',
    name: 'TM Gelartto',
    desc: 'Insegna: Gelartto - attacco Ice.',
    type: 'tm',
    price: 4000,
    effect: 'tm_gelartto',
    sprite: 'tm_ice',
  },
  tm_valanga: {
    id: 'tm_valanga',
    name: 'TM Valanga',
    desc: 'Insegna: Valanga - attacco Ice forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_valanga',
    sprite: 'tm_ice',
  },
  
  // EARTH TMs
  tm_terramoto: {
    id: 'tm_terramoto',
    name: 'TM Terramoto',
    desc: 'Insegna: Terramoto - attacco Terra devastante.',
    type: 'tm',
    price: 8000,
    effect: 'tm_terramoto',
    sprite: 'tm_earth',
  },
  tm_frana: {
    id: 'tm_frana',
    name: 'TM Frana',
    desc: 'Insegna: Frana - attacco Terra.',
    type: 'tm',
    price: 4000,
    effect: 'tm_frana',
    sprite: 'tm_earth',
  },
  
  // AIR TMs
  tm_spritzata: {
    id: 'tm_spritzata',
    name: 'TM Spritzata',
    desc: 'Insegna: Spritzata - attacco Air.',
    type: 'tm',
    price: 4000,
    effect: 'tm_spritzata',
    sprite: 'tm_air',
  },
  tm_tornado: {
    id: 'tm_tornado',
    name: 'TM Tornado',
    desc: 'Insegna: Tornado - attacco Air forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_tornado',
    sprite: 'tm_air',
  },
  
  // MAGIC TMs
  tm_magia: {
    id: 'tm_magia',
    name: 'TM Magia',
    desc: 'Insegna: Magia - attacco Magic base.',
    type: 'tm',
    price: 4000,
    effect: 'tm_magia',
    sprite: 'tm_magic',
  },
  tm_illusione: {
    id: 'tm_illusione',
    name: 'TM Illusione',
    desc: 'Insegna: Illusione - attacco Magic forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_illusione',
    sprite: 'tm_magic',
  },
  
  // PSYCHO TMs
  tm_psicic: {
    id: 'tm_psicic',
    name: 'TM Psicic',
    desc: 'Insegna: Psicic - attacco Psycho.',
    type: 'tm',
    price: 4000,
    effect: 'tm_psicic',
    sprite: 'tm_psycho',
  },
  tm_psicopsia: {
    id: 'tm_psicopsia',
    name: 'TM Psicopsia',
    desc: 'Insegna: Psicopsia - attacco Psycho forte.',
    type: 'tm',
    price: 6000,
    effect: 'tm_psicopsia',
    sprite: 'tm_psycho',
  },
  
  // SHADOW TMs
  tm_ombra: {
    id: 'tm_ombra',
    name: 'TM Ombra',
    desc: 'Insegna: Ombra - attacco Shadow.',
    type: 'tm',
    price: 4000,
    effect: 'tm_ombra',
    sprite: 'tm_shadow',
  },
  tm_notte_eterna: {
    id: 'tm_notte_eterna',
    name: 'TM Notte Eterna',
    desc: 'Insegna: Notte Eterna - attacco Shadow devastante.',
    type: 'tm',
    price: 8000,
    effect: 'tm_notteeterna',
    sprite: 'tm_shadow',
  },
  
  // DRAGON TMs
  tm_dragoartto: {
    id: 'tm_dragoartto',
    name: 'TM Dragoartto',
    desc: 'Insegna: Dragoartto - attacco Drago.',
    type: 'tm',
    price: 6000,
    effect: 'tm_dragoartto',
    sprite: 'tm_dragon',
  },
  tm_dragoforma: {
    id: 'tm_dragoforma',
    name: 'TM Dragoforma',
    desc: 'Insegna: Dragoforma - attacco Drago devastante.',
    type: 'tm',
    price: 10000,
    effect: 'tm_dragoforma',
    sprite: 'tm_dragon',
  },
  
  // STATUS TMs
  tm_veleno: {
    id: 'tm_veleno',
    name: 'TM Veleno',
    desc: 'Insegna: Veleno - avvelena il nemico.',
    type: 'tm',
    price: 3000,
    effect: 'tm_veleno',
    sprite: 'tm_status',
  },
  tm_paralisi: {
    id: 'tm_paralisi',
    name: 'TM Paralisi',
    desc: 'Insegna: Paralisi - paralizza il nemico.',
    type: 'tm',
    price: 3000,
    effect: 'tm_paralisi',
    sprite: 'tm_status',
  },
  tm_sonno: {
    id: 'tm_sonno',
    name: 'TM Sonno',
    desc: 'Insegna: Sonno - fa dormire il nemico.',
    type: 'tm',
    price: 3000,
    effect: 'tm_sonno',
    sprite: 'tm_status',
  },
  tm_conflagrazione: {
    id: 'tm_conflagrazione',
    name: 'TM Conflagrazione',
    desc: 'Insegna: Conflagrazione - ustiona il nemico.',
    type: 'tm',
    price: 4000,
    effect: 'tm_conflagrazione',
    sprite: 'tm_status',
  },
  
  // BUFF TMs
  tm_raffica: {
    id: 'tm_raffica',
    name: 'TM Raffica',
    desc: 'Insegna: Raffica - aumenta la velocità.',
    type: 'tm',
    price: 3500,
    effect: 'tm_raffica',
    sprite: 'tm_buff',
  },
  tm_corazza: {
    id: 'tm_corazza',
    name: 'TM Corazza',
    desc: 'Insegna: Corazza - aumenta la difesa.',
    type: 'tm',
    price: 3500,
    effect: 'tm_corazza',
    sprite: 'tm_buff',
  },
  tm_furia: {
    id: 'tm_furia',
    name: 'TM Furia',
    desc: 'Insegna: Furia - aumenta l\'attacco.',
    type: 'tm',
    price: 3500,
    effect: 'tm_furia',
    sprite: 'tm_buff',
  },
  tm_schermaglia: {
    id: 'tm_schermaglia',
    name: 'TM Schermaglia',
    desc: 'Insegna: Schermaglia - aumenta precisione.',
    type: 'tm',
    price: 3500,
    effect: 'tm_schermaglia',
    sprite: 'tm_buff',
  },
  tm_meditazione: {
    id: 'tm_meditazione',
    name: 'TM Meditazione',
    desc: 'Insegna: Meditazione - aumenta Sp. Atk.',
    type: 'tm',
    price: 4000,
    effect: 'tm_meditazione',
    sprite: 'tm_buff',
  },
  
  // HEAL TMs
  tm_ristoro: {
    id: 'tm_ristoro',
    name: 'TM Ristoro',
    desc: 'Insegna: Ristoro - cura il team.',
    type: 'tm',
    price: 5000,
    effect: 'tm_ristoro',
    sprite: 'tm_heal',
  },
  tm_bandaggio: {
    id: 'tm_bandaggio',
    name: 'TM Bandaggio',
    desc: 'Insegna: Bandaggio - recupera PS.',
    type: 'tm',
    price: 3500,
    effect: 'tm_bandaggio',
    sprite: 'tm_heal',
  },
  
  // UTILITY TMs
  tm_sostituto: {
    id: 'tm_sostituto',
    name: 'TM Sostituto',
    desc: 'Insegna: Sostituto - crea un doppio.',
    type: 'tm',
    price: 6000,
    effect: 'tm_sostituto',
    sprite: 'tm_utility',
  },
  tm_protezione: {
    id: 'tm_protezione',
    name: 'TM Protezione',
    desc: 'Insegna: Protezione - protegge un turno.',
    type: 'tm',
    price: 5000,
    effect: 'tm_protezione',
    sprite: 'tm_utility',
  },
  tm_calcolatore: {
    id: 'tm_calcolatore',
    name: 'TM Calcolatore',
    desc: 'Insegna: Calcolatore - previsioni di battaglia.',
    type: 'tm',
    price: 4000,
    effect: 'tm_calcolatore',
    sprite: 'tm_utility',
  },
  tm_teleport: {
    id: 'tm_teleport',
    name: 'TM Teleport',
    desc: 'Insegna: Teleport - fuggi dalla battaglia.',
    type: 'tm',
    price: 2000,
    effect: 'tm_teleport',
    sprite: 'tm_utility',
  },

  // ═══════════════════════════════════════════════════════════════════
  // HOLD ITEMS - Items that Besti can hold
  // ═══════════════════════════════════════════════════════════════════
  
  gioielli_veneti: {
    id: 'gioielli_veneti',
    name: 'Gioielli Veneti',
    desc: 'Aumenta l\'attacco se tenuto.',
    type: 'hold',
    price: 5000,
    effect: 'hold_attack_boost',
    sprite: 'jewel',
  },
  piuma_serenissima: {
    id: 'piuma_serenissima',
    name: 'Piuma Serenissima',
    desc: 'Aumenta la velocità se tenuto.',
    type: 'hold',
    price: 5000,
    effect: 'hold_speed_boost',
    sprite: 'piuma_serenissima',
  },
  scaglia_drago: {
    id: 'scaglia_drago',
    name: 'Scaglia di Drago',
    desc: 'Aumenta la potenza degli attacchi Drago.',
    type: 'hold',
    price: 8000,
    effect: 'hold_dragon_power',
    sprite: 'scaglia',
  },
  carbone_veneto: {
    id: 'carbone_veneto',
    name: 'Carbone Veneto',
    desc: 'Aumenta la potenza degli attacchi Fuoco.',
    type: 'hold',
    price: 4000,
    effect: 'hold_fire_power',
    sprite: 'carbone',
  },
  alga_laguna: {
    id: 'alga_laguna',
    name: 'Alga della Laguna',
    desc: 'Aumenta la potenza degli attacchi Acqua.',
    type: 'hold',
    price: 4000,
    effect: 'hold_water_power',
    sprite: 'alga',
  },
  radice_antica: {
    id: 'radice_antica',
    name: 'Radice Antica',
    desc: 'Recupera PS ogni turno.',
    type: 'hold',
    price: 6000,
    effect: 'hold_regen',
    sprite: 'radice',
  },
  amuleto_maschera: {
    id: 'amuleto_maschera',
    name: 'Amuleto Maschera',
    desc: 'Protegge da colpi critici.',
    type: 'hold',
    price: 10000,
    effect: 'hold_crit_protect',
    sprite: 'amuleto',
  },
  lente_psycho: {
    id: 'lente_psycho',
    name: 'Lente Psycho',
    desc: 'Aumenta attacchi Psycho e Magic.',
    type: 'hold',
    price: 7000,
    effect: 'hold_psycho_magic',
    sprite: 'lente',
  },
  uncino_terra: {
    id: 'uncino_terra',
    name: 'Uncino di Terra',
    desc: 'Aumenta attacco se c\'è Terra.',
    type: 'hold',
    price: 5000,
    effect: 'hold_terra_bonus',
    sprite: 'uncino',
  },
  pellet_polenta: {
    id: 'pellet_polenta',
    name: 'Pellet Polenta',
    desc: 'Aumenta difesa.',
    type: 'hold',
    price: 4000,
    effect: 'hold_defense_boost',
    sprite: 'pellet',
  },

  // ═══════════════════════════════════════════════════════════════════
  // SPECIAL & QUEST ITEMS
  // ═══════════════════════════════════════════════════════════════════
  
  foglia_loto: {
    id: 'foglia_loto',
    name: 'Foglia di Loto',
    desc: 'Rara foglia della laguna.',
    type: 'key',
    price: 0,
    effect: 'cure_paralysis',
    sprite: 'leaf',
  },
  maschera_burla: {
    id: 'maschera_burla',
    name: 'Maschera Burla',
    desc: 'Maschera per il carnevale.',
    type: 'key',
    price: 0,
    effect: 'story_carnevale',
    sprite: 'mask',
  },
  
  // QUEST ITEMS
  biglietto_gratis: {
    id: 'biglietto_gratis',
    name: 'Biglietto Gratis',
    desc: 'Biglietto della lotteria.',
    type: 'key',
    price: 0,
    effect: 'quest_lottery',
    sprite: 'biglietto',
  },
  ricetta_segreta: {
    id: 'ricetta_segreta',
    name: 'Ricetta Segreta',
    desc: 'Ricetta dello spritz perfetto.',
    type: 'key',
    price: 0,
    effect: 'quest_ricetta',
    sprite: 'ricetta',
  },
  foto_souvenir: {
    id: 'foto_souvenir',
    name: 'Foto Souvenir',
    desc: 'Foto ricordo di Venetia.',
    type: 'key',
    price: 0,
    effect: 'quest_foto',
    sprite: 'foto',
  },
  sigillo_doge: {
    id: 'sigillo_doge',
    name: 'Sigillo del Doge',
    desc: 'Sigillo ufficiale del Doge.',
    type: 'key',
    price: 0,
    effect: 'quest_sigillo',
    sprite: 'sigillo',
  },
  map_canalborgo: {
    id: 'map_canalborgo',
    name: 'Mappa di Canalborgo',
    desc: 'Mappa base della tua citta natale.',
    type: 'key',
    price: 0,
    effect: 'map_unlock',
    sprite: 'mappa',
  },
  pokedex: {
    id: 'pokedex',
    name: 'PokeDioex',
    desc: 'Enciclopedia ufficiale dei Besti di Venetia, distribuita nei Centri Besti e in alcune botteghe.',
    type: 'key',
    price: 0,
    effect: 'bestidex_unlock',
    sprite: 'diario',
  },
  pozione: {
    id: 'pozione',
    name: 'Pozione',
    desc: 'Alias classico della Pozioncino per ricompense e missioni.',
    type: 'heal',
    price: 100,
    val: 20,
    effect: 'heal',
    sprite: 'potion',
  },
  radicchio_dorato: {
    id: 'radicchio_dorato',
    name: 'Radicchio Dorato',
    desc: 'Radicchio rarissimo, prezioso per le missioni di Trevisella.',
    type: 'key',
    price: 0,
    effect: 'quest_radicchio',
    sprite: 'radicchio',
  },
  carta_studente: {
    id: 'carta_studente',
    name: 'Carta Studente',
    desc: 'Tessera universitaria di Padoana.',
    type: 'key',
    price: 0,
    effect: 'quest_studente',
    sprite: 'biglietto',
  },
  pietra_natura: {
    id: 'pietra_natura',
    name: 'Pietra Natura',
    desc: 'Pietra verde usata nelle missioni secondarie.',
    type: 'stone',
    price: 900,
    effect: 'nature_evo',
    sprite: 'leaf_stone',
  },
  badge_campione: {
    id: 'badge_campione',
    name: 'Badge Campione',
    desc: 'Simbolo della tua vittoria finale nella Lega.',
    type: 'key',
    price: 0,
    effect: 'story_champion',
    sprite: 'sigillo',
  },
  coppa_venetia: {
    id: 'coppa_venetia',
    name: 'Coppa di Venetia',
    desc: 'Trofeo assegnato al nuovo Campione.',
    type: 'key',
    price: 0,
    effect: 'story_trophy',
    sprite: 'sigillo',
  },
  medaglia_eroe: {
    id: 'medaglia_eroe',
    name: 'Medaglia Eroe',
    desc: 'Medaglia per chi salva Venetia dalla Polenta.',
    type: 'key',
    price: 0,
    effect: 'story_hero',
    sprite: 'sigillo',
  },
  carta_sconto: {
    id: 'carta_sconto',
    name: 'Carta Sconto',
    desc: 'Carta fedelta che promette prezzi migliori nei negozi.',
    type: 'key',
    price: 0,
    effect: 'shop_discount',
    sprite: 'biglietto',
  },
  cattura_master: {
    id: 'cattura_master',
    name: 'Titolo Cattura Master',
    desc: 'Riconoscimento per i migliori catturatori di Besti.',
    type: 'key',
    price: 0,
    effect: 'capture_master',
    sprite: 'sigillo',
  },
  bestidex_nazionale: {
    id: 'bestidex_nazionale',
    name: 'PokeDioex Nazionale',
    desc: 'Aggiornamento completo del PokeDioex con tutte le regioni note.',
    type: 'key',
    price: 0,
    effect: 'bestidex_national',
    sprite: 'diario',
  },
  tesoro_leggendario: {
    id: 'tesoro_leggendario',
    name: 'Tesoro Leggendario',
    desc: 'Un tesoro antico trovato nelle esplorazioni piu rare.',
    type: 'key',
    price: 0,
    effect: 'treasure_legend',
    sprite: 'sigillo',
  },
  badge_gondola: {
    id: 'badge_gondola',
    name: 'Badge Gondola',
    desc: 'Badge speciale del vecchio gym segreto di Canalborgo.',
    type: 'key',
    price: 0,
    effect: 'story_badge_gondola',
    sprite: 'gondola_gold',
  },
}

export const SHOP_ITEMS = {
  basics: [
    ITEMS.pozioncino,
    ITEMS.gondolball,
    ITEMS.caffette,
    ITEMS.acqua_sanita,
    ITEMS.profumo_veneto,
  ],
  spritzia: [
    ITEMS.pozioncino,
    ITEMS.superpozione,
    ITEMS.gondolball,
    ITEMS.mascheraball,
    ITEMS.spritzball,
    ITEMS.pietra_focaia,
    ITEMS.pietra_acquatica,
    ITEMS.pietra_tuono,
    ITEMS.caffette,
    ITEMS.spritz_curativo,
    ITEMS.acqua_sanita,
    ITEMS.profumo_veneto,
  ],
  veronara: [
    ITEMS.superpozione,
    ITEMS.iperpozione,
    ITEMS.spritzball,
    ITEMS.polentaball,
    ITEMS.pietra_verde,
    ITEMS.pietra_polenta,
    ITEMS.pietra_tuono,
    ITEMS.pietra_ghiaccio,
    ITEMS.paninoVeneto,
    ITEMS.tagliatelle,
    ITEMS.maxpozione,
  ],
  padova: [
    ITEMS.pozioncino,
    ITEMS.gondolball,
    ITEMS.superpozione,
    ITEMS.pietra_temporale,
    ITEMS.pietra_maschera,
    ITEMS.pietra_ombra,
    ITEMS.pietra_luna,
    ITEMS.pietra_sole,
    ITEMS.serenaball,
    ITEMS.graticciaball,
  ],
  treviso: [
    ITEMS.pozioncino,
    ITEMS.spritz_curativo,
    ITEMS.gondolball,
    ITEMS.scampaball,
    ITEMS.aereoball,
    ITEMS.pietra_acquatica,
    ITEMS.pietra_verde,
    ITEMS.caffette,
    ITEMS.frittura_mista,
    ITEMS.lagunaball,
  ],
  dolomax: [
    ITEMS.iperpozione,
    ITEMS.maxpozione,
    ITEMS.polentaball,
    ITEMS.montagnaball,
    ITEMS.pietra_ghiaccio,
    ITEMS.pietra_terra,
    ITEMS.pietra_alba,
    ITEMS.pietra_tramonto,
    ITEMS.frittura_mista,
    ITEMS.revive,
  ],
  gardalago: [
    ITEMS.maxpozione,
    ITEMS.frittura_mista,
    ITEMS.dragoball,
    ITEMS.graticciaball,
    ITEMS.pietra_drago,
    ITEMS.pietra_fulmine,
    ITEMS.pietra_alba,
    ITEMS.pietra_tramonto,
    ITEMS.maxrevive,
    ITEMS.fossile_uovo,
  ],
}

export const STARTER_ITEMS = [
  ITEMS.pozioncino,
  ITEMS.gondolball,
  ITEMS.gondolball,
  ITEMS.gondolball,
  ITEMS.caffette,
  ITEMS.acqua_sanita,
]

// Item categories for organization
export const ITEM_CATEGORIES = {
  capture: [
    'gondolball', 'mascheraball', 'spritzball', 'polentaball', 'scampaball',
    'vinoball', 'lagunaball', 'montagnaball', 'aereoball', 'graticciaball',
    'serenaball', 'dragoball', 'fantasmaball', 'dogeball', 'carnevaleball'
  ],
  healing: [
    'pozioncino', 'superpozione', 'iperpozione', 'maxpozione',
    'spritz_curativo', 'caffette', 'paninoVeneto', 'tagliatelle',
    'frittura_mista', 'grappa_medicinale', 'revive', 'maxrevive'
  ],
  status_cure: [
    'acqua_sanita', 'profumo_veneto', 'incenso_pace', 'sonnifero',
    'acqua_benedetta', 'foglia_loto'
  ],
  stones: [
    'pietra_focaia', 'pietra_acquatica', 'pietra_tuono', 'pietra_verde',
    'pietra_ghiaccio', 'pietra_luna', 'pietra_sole', 'pietra_alba',
    'pietra_tramonto', 'pietra_fulmine', 'pietra_temporale', 'pietra_polenta',
    'pietra_maschera', 'pietra_ombra', 'pietra_drago'
  ],
  key: [
    'biglietto_treno', 'scooterino', 'biciRubata', 'barchino', 'gondola_oro',
    'chiavi_casa', 'pacco_sospetto', 'mantello_polenta', 'diario_doge',
    'maschera_doge', 'anello_doge', 'mappa_antica', 'chiave_segreta',
    'fossile_uovo', 'piuma_verde', 'lettera_amore', 'amuleto_veneto'
  ],
  tms: [
    'tm_brusco', 'tm_colpo', 'tm_fuocartto', 'tm_inferno', 'tm_ondata',
    'tm_tsunami', 'tm_scossa', 'tm_fulmine', 'tm_erba alta', 'tm_tempesta',
    'tm_gelartto', 'tm_valanga', 'tm_terramoto', 'tm_frana', 'tm_spritzata',
    'tm_tornado', 'tm_magia', 'tm_illusione', 'tm_psicic', 'tm_psicopsia',
    'tm_ombra', 'tm_notte_eterna', 'tm_dragoartto', 'tm_dragoforma'
  ],
  hold: [
    'gioielli_veneti', 'piuma_serenissima', 'scaglia_drago', 'carbone_veneto',
    'alga_laguna', 'radice_antica', 'amuleto_maschera', 'lente_psycho',
    'uncino_terra', 'pellet_polenta'
  ]
}
